defmodule GgenIgniter.SemanticJiraPackTest do
  @moduledoc """
  Chicago-style, no-mocks integration proof for semantic-jira-pack.

  Uses the real Core-profile pack manifest admission, RDF/Turtle loader, SPARQL
  engine, for-each Reactor render/admission/actuation path, real filesystem,
  real nested mix compile verification, and durable GgenIgniter receipts.
  """

  use ExUnit.Case, async: false

  @moduletag :integration

  alias GgenIgniter.Receipt

  @ontology_path "priv/ggen/semantic-jira-pack/ontology.ttl"

  defp scratch_dir!(tag) do
    dir =
      Path.join(
        System.tmp_dir!(),
        "ggen_igniter_semantic_jira_#{tag}_#{System.unique_integer([:positive])}"
      )

    File.rm_rf!(dir)
    File.mkdir_p!(dir)
    on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  defp run_sync(work_dir, extra_args \\ []) do
    out_template = Path.join(work_dir, "<%= id %>.md")

    args = [
      "ggen_igniter.sync",
      "--engine",
      "sparql",
      "--pack",
      "semantic-jira-pack",
      "--out",
      out_template,
      "--manifest-dir",
      work_dir,
      "--verify-cwd",
      File.cwd!()
    ]

    System.cmd("mix", args ++ extra_args,
      cd: File.cwd!(),
      stderr_to_stdout: true
    )
  end

  defp sha256_file(path) do
    "sha256:" <>
      (:crypto.hash(:sha256, File.read!(path))
       |> Base.encode16(case: :lower))
  end

  describe "canonical WorkOrder graph -> deterministic Markdown projection -> graph-bound receipt" do
    test "manufactures one ticket per admitted WorkOrder and replays byte-identically" do
      work_dir = scratch_dir!("projection")
      output_path = Path.join(work_dir, "SJ-001.md")

      {first_output, first_exit} = run_sync(work_dir)

      assert first_exit == 0, "first Semantic Jira sync failed:\n#{first_output}"
      assert File.exists?(output_path)

      first_bytes = File.read!(output_path)

      assert first_bytes =~
               "<!-- GENERATED by semantic-jira-pack from canonical RDF WorkOrder"

      assert first_bytes =~ "# SJ-001 — Manufacture Semantic Jira work orders from RDF"
      assert first_bytes =~ "**Base SHA:** d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3"
      assert first_bytes =~ "**Standing:** UNKNOWN"
      assert first_bytes =~ "**Authority ceiling:** CONSTRUCT"
      assert first_bytes =~ "zero independent actuation"
      assert first_bytes =~ "Missing required field still renders"
      assert first_bytes =~ "Add a qualified SHACL court"

      [first_receipt] = Receipt.read_all!(work_dir)
      assert first_receipt["standing"] == "alive"
      assert output_path in first_receipt["files"]
      assert first_receipt["metadata"]["graph_hash"] == sha256_file(@ontology_path)

      {second_output, second_exit} = run_sync(work_dir)

      assert second_exit == 0, "second Semantic Jira sync failed:\n#{second_output}"
      assert File.read!(output_path) == first_bytes

      receipts = Receipt.read_all!(work_dir)
      assert length(receipts) == 2

      [first_graph_hash, second_graph_hash] =
        Enum.map(receipts, &get_in(&1, ["metadata", "graph_hash"]))

      assert first_graph_hash == second_graph_hash
      assert second_graph_hash == sha256_file(@ontology_path)
    end
  end

  describe "semantic admission falsifier" do
    test "removing a required baseSha refuses before any ticket is actuated" do
      work_dir = scratch_dir!("missing_base_sha")
      broken_ontology = Path.join(work_dir, "missing-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/^    sj:baseSha "[0-9a-f]+" ;\n/m,
          "",
          global: false
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, [
          "--ontology",
          broken_ontology
        ])

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing core field base_sha"
      refute File.exists?(Path.join(work_dir, "SJ-001.md"))

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end
end
