defmodule GgenIgniter.ReceiptedExtensionPackTest do
  @moduledoc """
  Chicago-style: real `mix ggen_igniter.sync` subprocesses render
  `priv/ggen/receipted-extension-pack` into a real tmp dir; the real compiler
  builds the rendered Spark extension against the real ash + spark deps; and
  real Ash resources are compiled with and without a declared receipt.

  Falsifier: a resource using the extension with NO `receipted do receipt ... end`
  must fail compilation with a real `Spark.Error.DslError` (REFUSED_NO_RECEIPT).
  """

  use ExUnit.Case, async: false
  # async: false -- compiles modules into the global code server and shares Ash config.

  @pack "receipted-extension-pack"
  @pack_dir Path.expand("../priv/ggen/#{@pack}", __DIR__)
  @fixture Path.expand("fixtures/receipted-extension/consumer.ttl", __DIR__)
  @ext ReceiptedFixture.Receipted

  setup_all do
    dir = Path.join(System.tmp_dir!(), "receipted_ext_#{System.unique_integer([:positive])}")
    File.rm_rf!(dir)
    File.mkdir_p!(dir)
    on_exit(fn -> File.rm_rf!(dir) end)

    ontology = Path.join(dir, "consumer.ttl")

    File.write!(
      ontology,
      File.read!(Path.join(@pack_dir, "ontology.ttl")) <> "\n" <> File.read!(@fixture)
    )

    results =
      for {stem, out} <- [
            {"extension", "lib/receipted_fixture/receipted.ex"},
            {"verifier", "lib/receipted_fixture/receipted_verifier.ex"}
          ] do
        {output, exit} =
          System.cmd(
            "mix",
            [
              "ggen_igniter.sync",
              "--pack",
              "#{@pack}:#{stem}",
              "--ontology",
              ontology,
              "--out",
              Path.join(dir, out),
              "--manifest-dir",
              dir,
              "--verify-cwd",
              File.cwd!()
            ],
            cd: File.cwd!(),
            stderr_to_stdout: true
          )

        {stem, exit, output, Path.join(dir, out)}
      end

    %{dir: dir, results: results}
  end

  defp compile_generated!(results) do
    paths = for {_, 0, _, path} <- results, do: path
    ebin = Path.join(System.tmp_dir!(), "receipted_ebin_#{System.unique_integer([:positive])}")
    File.mkdir_p!(ebin)
    previous = Code.get_compiler_option(:ignore_module_conflict)
    Code.put_compiler_option(:ignore_module_conflict, true)

    try do
      {:ok, _mods, %{compile_warnings: [], runtime_warnings: []}} =
        Kernel.ParallelCompiler.compile_to_path(paths, ebin, return_diagnostics: true)

      true = :code.add_patha(String.to_charlist(ebin))
    after
      Code.put_compiler_option(:ignore_module_conflict, previous)
    end
  end

  # Spark verifiers run in the compiler's after-compile parallel checker, so a
  # refusal surfaces as a compile diagnostic (a hard failure under the
  # `--warnings-as-errors` bar every consumer build carries), not as a raise
  # from `Code.compile_string/2`. Returns `{modules, diagnostics}` from a real
  # `Kernel.ParallelCompiler` run over a real file.
  defp compile_resource(name, body) do
    source = """
    defmodule #{name} do
      use Ash.Resource,
        data_layer: Ash.DataLayer.Ets,
        domain: nil,
        validate_domain_inclusion?: false,
        extensions: [#{inspect(@ext)}]

      attributes do
        uuid_primary_key :id
      end

    #{body}
    end
    """

    dir = Path.join(System.tmp_dir!(), "receipted_res_#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)
    path = Path.join(dir, "resource.ex")
    File.write!(path, source)

    try do
      case Kernel.ParallelCompiler.compile_to_path([path], Path.join(dir, "ebin"),
             return_diagnostics: true
           ) do
        {:ok, modules, %{compile_warnings: cw, runtime_warnings: rw}} ->
          {:ok, modules,
           (cw ++ rw)
           |> Enum.map(&diagnostic_text/1)
           |> Enum.reject(&(&1 =~ "already been consolidated"))}

        {:error, errors, %{compile_warnings: cw, runtime_warnings: rw}} ->
          {:error, Enum.map(errors, &diagnostic_text/1),
           (cw ++ rw)
           |> Enum.map(&diagnostic_text/1)
           |> Enum.reject(&(&1 =~ "already been consolidated"))}
      end
    after
      File.rm_rf!(dir)
    end
  end

  defp diagnostic_text(%{message: m}), do: to_string(m)
  defp diagnostic_text(other), do: inspect(other)

  test "rendering exits 0 and the extension appears only in rendered output", %{results: results} do
    for {stem, exit, output, path} <- results do
      assert exit == 0, "#{stem} render failed: #{output}"
      assert File.read!(path) =~ "GENERATED by receipted-extension-pack"
    end

    ext = results |> Enum.find(&(elem(&1, 0) == "extension")) |> elem(3) |> File.read!()
    assert ext =~ "use Spark.Dsl.Extension"

    # No hand-written `use Spark.Dsl.Extension` under lib/.
    hits =
      "lib/**/*.ex"
      |> Path.wildcard()
      |> Enum.filter(&(File.read!(&1) =~ "use Spark.Dsl.Extension"))

    assert hits == []
  end

  test "resource WITH a receipt compiles; resource WITHOUT is refused", %{results: results} do
    compile_generated!(results)

    Application.put_env(:ash, :validate_domain_config_inclusion?, false)
    previous = Code.get_compiler_option(:ignore_module_conflict)
    Code.put_compiler_option(:ignore_module_conflict, true)

    try do
      assert {:ok, modules, []} =
               compile_resource("ReceiptedFixture.WithReceipt", """
                 receipted do
                   receipt :order_receipt
                 end
               """)

      assert ReceiptedFixture.WithReceipt in modules
      assert @ext.receipts(ReceiptedFixture.WithReceipt) == [:order_receipt]

      # The falsifier: no receipt declared -> the verifier's DslError is reported.
      {_status, _mods_or_errors, diagnostics} =
        case compile_resource("ReceiptedFixture.NoReceipt", "") do
          {:ok, m, d} -> {:ok, m, d}
          {:error, e, d} -> {:error, e, d ++ e}
        end

      assert Enum.any?(diagnostics, &(&1 =~ "REFUSED_NO_RECEIPT")),
             "resource with no receipt compiled clean: verifier is vacuous: #{inspect(diagnostics)}"

      assert Enum.any?(diagnostics, &(&1 =~ "Spark.Error.DslError")) or
               Enum.any?(diagnostics, &(&1 =~ "receipted"))
    after
      Code.put_compiler_option(:ignore_module_conflict, previous)
      Application.delete_env(:ash, :validate_domain_config_inclusion?)
    end
  end
end
