defmodule GgenIgniter.SemanticJiraPackTest do
  @moduledoc """
  Chicago-style, no-mocks integration proof for semantic-jira-pack.

  Uses the real Core-profile pack manifest admission, RDF/Turtle loader, SPARQL
  engine, for-each Reactor render/admission/actuation path, real filesystem,
  real nested mix compile verification, and durable GgenIgniter receipts.
  """

  use ExUnit.Case, async: false

  @moduletag :integration

  alias GgenIgniter.{Receipt, SemanticJira}

  @ontology_path "priv/ggen/semantic-jira-pack/ontology.ttl"

  defp scratch_dir!(tag) do
    dir =
      Path.join(
        System.tmp_dir!(),
        "ggen_igniter_semantic_jira_#{tag}_#{System.unique_integer([:positive])}"
      )

    File.rm_rf!(dir)
    File.mkdir_p!(dir)

    # The receipt layer stores realpath'd (/private/var/...) file keys while
    # System.tmp_dir!() hands out /var/... on macOS; return the real path so
    # path expectations match the SUT's canonical storage (bccf084 pattern).
    dir = RealDir.real_dir!(dir)

    on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  defp run_sync(
         work_dir,
         extra_args \\ [],
         pack \\ "semantic-jira-pack:jira",
         out_suffix \\ ".md",
         out_file \\ nil
       ) do
    # Per-row templates fan out through `<%= id %>`; per-run templates (the
    # OCEL log) render ONE fixed file, so the caller passes a literal
    # `out_file` instead.
    out_template =
      if out_file do
        Path.join(work_dir, out_file)
      else
        Path.join(work_dir, "<%= id %>#{out_suffix}")
      end

    args = [
      "ggen_igniter.sync",
      "--engine",
      "sparql",
      "--pack",
      pack,
      "--out",
      out_template,
      "--manifest-dir",
      work_dir,
      "--verify-cwd",
      File.cwd!()
    ]

    System.cmd("mix", args ++ extra_args,
      cd: File.cwd!(),
      stderr_to_stdout: true
    )
  end

  defp sha256_file(path) do
    "sha256:" <>
      (:crypto.hash(:sha256, File.read!(path))
       |> Base.encode16(case: :lower))
  end

  describe "canonical WorkOrder graph -> deterministic Markdown projection -> graph-bound receipt" do
    test "manufactures all canonical WorkOrders and replays byte-identically" do
      work_dir = scratch_dir!("projection")
      output_path = Path.join(work_dir, "SJ-001.md")

      {first_output, first_exit} = run_sync(work_dir)

      assert first_exit == 0, "first Semantic Jira sync failed:\n#{first_output}"
      assert File.exists?(output_path)
      assert File.exists?(Path.join(work_dir, "GALL-001.md"))
      assert File.exists?(Path.join(work_dir, "GALL-032.md"))
      assert length(Path.wildcard(Path.join(work_dir, "*.md"))) == 33

      first_bytes = File.read!(output_path)

      assert first_bytes =~
               "<!-- GENERATED by semantic-jira-pack from canonical RDF WorkOrder"

      assert first_bytes =~ "# SJ-001 — Manufacture Semantic Jira work orders from RDF"
      assert first_bytes =~ "**Base SHA:** d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3"
      assert first_bytes =~ "**Standing:** UNKNOWN"
      assert first_bytes =~ "**Authority ceiling:** CONSTRUCT"
      assert first_bytes =~ "zero independent actuation"
      assert first_bytes =~ "Missing required field still renders"
      assert first_bytes =~ "Add a qualified SHACL court"

      [first_receipt] = Receipt.read_all!(work_dir)
      assert first_receipt["standing"] == "alive"
      assert output_path in first_receipt["files"]
      assert first_receipt["metadata"]["graph_hash"] == sha256_file(@ontology_path)

      {second_output, second_exit} = run_sync(work_dir)

      assert second_exit == 0, "second Semantic Jira sync failed:\n#{second_output}"
      assert File.read!(output_path) == first_bytes

      receipts = Receipt.read_all!(work_dir)
      assert length(receipts) == 2

      [first_graph_hash, second_graph_hash] =
        Enum.map(receipts, &get_in(&1, ["metadata", "graph_hash"]))

      assert first_graph_hash == second_graph_hash
      assert second_graph_hash == sha256_file(@ontology_path)
    end
  end

  describe "PRD projection template" do
    test "manufactures the PRD projection for dogfood SJ-001 and replays byte-identically" do
      work_dir = scratch_dir!("prd_projection")
      output_path = Path.join(work_dir, "SJ-001.prd.md")

      {first_output, first_exit} =
        run_sync(work_dir, [], "semantic-jira-pack:prd", ".prd.md")

      assert first_exit == 0, "first PRD sync failed:\n#{first_output}"
      assert File.exists?(output_path)
      assert File.exists?(Path.join(work_dir, "GALL-001.prd.md"))
      assert File.exists?(Path.join(work_dir, "GALL-032.prd.md"))
      assert length(Path.wildcard(Path.join(work_dir, "*.prd.md"))) == 33

      first_bytes = File.read!(output_path)

      assert first_bytes =~
               "<!-- GENERATED by semantic-jira-pack from canonical RDF WorkOrder"

      assert first_bytes =~ "# PRD: SJ-001 — Manufacture Semantic Jira work orders from RDF"
      assert first_bytes =~ "**Base SHA:** d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3"
      assert first_bytes =~ "**Standing:** UNKNOWN"
      assert first_bytes =~ "**Exact subject:** semantic-jira-pack:work-order-projection"
      assert first_bytes =~ "zero independent actuation"
      assert first_bytes =~ "Canonical RDF source"
      assert first_bytes =~ "Missing required field still renders"
      assert first_bytes =~ "Add a qualified SHACL court"
      assert first_bytes =~ "Product requirements document"
      assert first_bytes =~ "priv/ggen/semantic-jira-pack"
      refute first_bytes =~ "TODO"
      refute first_bytes =~ "PLACEHOLDER"

      [first_receipt] = Receipt.read_all!(work_dir)
      assert first_receipt["standing"] == "alive"
      assert output_path in first_receipt["files"]
      assert first_receipt["metadata"]["graph_hash"] == sha256_file(@ontology_path)

      {second_output, second_exit} =
        run_sync(work_dir, [], "semantic-jira-pack:prd", ".prd.md")

      assert second_exit == 0, "second PRD sync failed:\n#{second_output}"
      assert File.read!(output_path) == first_bytes

      receipts = Receipt.read_all!(work_dir)
      assert length(receipts) == 2

      [first_graph_hash, second_graph_hash] =
        Enum.map(receipts, &get_in(&1, ["metadata", "graph_hash"]))

      assert first_graph_hash == second_graph_hash
      assert second_graph_hash == sha256_file(@ontology_path)
    end

    test "removing a required baseSha refuses the PRD projection before any file is actuated" do
      work_dir = scratch_dir!("prd_missing_base_sha")
      broken_ontology = Path.join(work_dir, "missing-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/^    sj:baseSha "[0-9a-f]+" ;\n/m,
          "",
          global: false
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, ["--ontology", broken_ontology], "semantic-jira-pack:prd", ".prd.md")

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing core field base_sha"
      refute File.exists?(Path.join(work_dir, "SJ-001.prd.md"))

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end

  describe "HDDL planning projection template" do
    test "manufactures the HDDL plan projection for the dogfood set and replays byte-identically" do
      work_dir = scratch_dir!("hddl_projection")
      output_path = Path.join(work_dir, "SJ-001.hddl")

      {first_output, first_exit} =
        run_sync(work_dir, [], "semantic-jira-pack:plan", ".hddl")

      assert first_exit == 0, "first HDDL sync failed:\n#{first_output}"
      assert File.exists?(output_path)
      assert File.exists?(Path.join(work_dir, "GALL-001.hddl"))
      assert File.exists?(Path.join(work_dir, "GALL-032.hddl"))
      assert length(Path.wildcard(Path.join(work_dir, "*.hddl"))) == 33

      first_bytes = File.read!(output_path)

      assert first_bytes =~
               ";; GENERATED by semantic-jira-pack from canonical RDF WorkOrder"

      # Zero-authority header convention, adapted to HDDL comment syntax.
      assert first_bytes =~ "Zero-authority projection"
      assert first_bytes =~ "holds no authority"
      assert first_bytes =~ "plan-as-declared"

      # State features are the graph's own boundary scalars as declared
      # constants; the observed standing in :init is never the goal standing.
      assert first_bytes =~ "(defproblem promote-SJ-001 semantic-jira-workorder"
      assert first_bytes =~ "(standing SJ-001 UNKNOWN)"
      assert first_bytes =~ "(base-sha SJ-001 d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3)"
      assert first_bytes =~ "(authority-ceiling SJ-001 CONSTRUCT)"

      # Subtasks are one per graph-fact satisfaction, derived only from the
      # canonical graph (ids, labels, and checkpoint ids included).
      assert first_bytes =~ "(close-court SJ-001 exact-head-projection-court)"
      assert first_bytes =~ "(produce-evidence SJ-001 graph-receipt-evidence)"
      assert first_bytes =~ "(record-receipt-class SJ-001 manufacture)"
      assert first_bytes =~ "(record-receipt-class SJ-001 projection)"
      assert first_bytes =~ "(record-receipt-class SJ-001 replay)"
      assert first_bytes =~ "(record-receipt-class SJ-001 verification)"
      assert first_bytes =~ "(discharge-falsifier SJ-001 missing-required-field-renders)"
      assert first_bytes =~ "(discharge-falsifier SJ-001 projection-gains-authority)"
      assert first_bytes =~ ";; Missing required field still renders"
      assert first_bytes =~ ";; Projection gains authority"
      assert first_bytes =~ "(reach-checkpoint SJ-001 shacl-admission-checkpoint)"

      # ALIVE-with-receipt is the declared goal, never the observed state.
      assert first_bytes =~ "(:goal (and (standing SJ-001 ALIVE) (has-receipt SJ-001)))"

      refute first_bytes =~ "TODO"
      refute first_bytes =~ "PLACEHOLDER"

      [first_receipt] = Receipt.read_all!(work_dir)
      assert first_receipt["standing"] == "alive"
      assert output_path in first_receipt["files"]
      assert first_receipt["metadata"]["graph_hash"] == sha256_file(@ontology_path)

      {second_output, second_exit} =
        run_sync(work_dir, [], "semantic-jira-pack:plan", ".hddl")

      assert second_exit == 0, "second HDDL sync failed:\n#{second_output}"
      assert File.read!(output_path) == first_bytes

      receipts = Receipt.read_all!(work_dir)
      assert length(receipts) == 2

      [first_graph_hash, second_graph_hash] =
        Enum.map(receipts, &get_in(&1, ["metadata", "graph_hash"]))

      assert first_graph_hash == second_graph_hash
      assert second_graph_hash == sha256_file(@ontology_path)
    end

    test "every dogfood plan is a balanced s-expression bound to its graph tokens" do
      work_dir = scratch_dir!("hddl_structure")
      {output, exit_code} = run_sync(work_dir, [], "semantic-jira-pack:plan", ".hddl")

      assert exit_code == 0, "HDDL sync failed:\n#{output}"

      paths = Path.wildcard(Path.join(work_dir, "*.hddl"))
      assert length(paths) == 33

      for path <- paths do
        id = Path.basename(path, ".hddl")
        bytes = File.read!(path)

        # Comments and quoted strings carry prose; the code skeleton must be
        # balanced well-formed s-expressions on its own.
        stripped =
          bytes
          |> String.replace(~r/;;[^\n]*/, "")
          |> String.replace(~r/"(?:[^"\\]|\\.)*"/, "")

        count = fn sub -> length(String.split(stripped, sub)) - 1 end

        assert count.("(") == count.(")"),
               "#{Path.basename(path)} has unbalanced parentheses"

        assert bytes =~ "(defproblem promote-#{id} semantic-jira-workorder"
        assert bytes =~ "(workorder #{id})"
        assert bytes =~ "(projection-authority NONE)"
        assert bytes =~ "(has-receipt #{id})"
      end

      # GALL-002 carries the graph's own typed dependency structure.
      gall_002 = File.read!(Path.join(work_dir, "GALL-002.hddl"))
      assert gall_002 =~ "edge-002-from-001 - dependency-edge"
      assert gall_002 =~ "(depends-on GALL-002 edge-002-from-001)"
      assert gall_002 =~ "(close-court GALL-002 court-gall-002)"
      assert gall_002 =~ "(produce-evidence GALL-002 source-evidence)"
      assert gall_002 =~ "(discharge-falsifier GALL-002 falsifier-gall-002)"
      assert gall_002 =~ "(reach-checkpoint GALL-002 gall-003)"
    end

    test "removing a required baseSha refuses the HDDL projection before any file is actuated" do
      work_dir = scratch_dir!("hddl_missing_base_sha")
      broken_ontology = Path.join(work_dir, "missing-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/^    sj:baseSha "[0-9a-f]+" ;\n/m,
          "",
          global: false
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, ["--ontology", broken_ontology], "semantic-jira-pack:plan", ".hddl")

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing core field base_sha"
      refute File.exists?(Path.join(work_dir, "SJ-001.hddl"))

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end

  describe "OCEL event-log projection" do
    test "manufactures one parseable OCEL log per run and replays byte-identically" do
      work_dir = scratch_dir!("ocel_projection")
      output_path = Path.join(work_dir, "ocel.json")

      {first_output, first_exit} =
        run_sync(work_dir, [], "semantic-jira-pack:ocel", "", "ocel.json")

      assert first_exit == 0, "first OCEL sync failed:\n#{first_output}"

      # ONE log document per manufacture run, not one file per WorkOrder.
      assert [^output_path] = Path.wildcard(Path.join(work_dir, "*.json"))

      first_bytes = File.read!(output_path)
      assert {:ok, log} = JSON.decode(first_bytes)

      assert log["authority"] == "NONE"
      assert log["generated_by"] =~ "semantic-jira-pack"
      assert log["authority_statement"] =~ "zero independent"

      objects = log["ocel:objects"]
      events = log["ocel:events"]
      relationships = log["ocel:relationships"]

      # One WorkOrder object per canonical WorkOrder, boundary attributes bound.
      work_order_objects = Enum.filter(objects, &(&1["ocel:type"] == "WorkOrder"))
      assert length(work_order_objects) == 33

      object_ids = Enum.map(objects, & &1["ocel:id"])
      assert length(object_ids) == length(Enum.uniq(object_ids))

      identifiers = Enum.map(work_order_objects, & &1["ocel:attributes"]["id"])
      assert "SJ-001" in identifiers
      assert "GALL-001" in identifiers
      assert "GALL-032" in identifiers

      dogfood = Enum.find(work_order_objects, &(&1["ocel:attributes"]["id"] == "SJ-001"))
      dogfood_attrs = dogfood["ocel:attributes"]

      assert dogfood_attrs["standing"] == "UNKNOWN"
      assert dogfood_attrs["baseSha"] == "d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3"
      assert dogfood_attrs["authorityCeiling"] == "CONSTRUCT"
      assert is_binary(dogfood_attrs["evidenceCeiling"])

      # Exactly the five admission-relevant event families, every event typed.
      event_types = events |> Enum.map(& &1["ocel:type"]) |> Enum.uniq() |> Enum.sort()

      assert event_types == [
               "checkpoint-set",
               "court-required",
               "evidence-required",
               "falsifier-registered",
               "projection-listed"
             ]

      # A parseable object-event graph: unique ids, every relationship
      # endpoint resolves to a real object, every flattened relationship
      # references a real event.
      assert length(events) == length(Enum.uniq(Enum.map(events, & &1["ocel:id"])))

      object_id_set = MapSet.new(object_ids)
      event_id_set = MapSet.new(Enum.map(events, & &1["ocel:id"]))

      Enum.each(events, fn event ->
        assert event["ocel:relationships"] != []

        Enum.each(event["ocel:relationships"], fn relationship ->
          assert MapSet.member?(object_id_set, relationship["ocel:object"])
        end)
      end)

      assert length(relationships) >= 2 * length(events)

      Enum.each(relationships, fn relationship ->
        assert MapSet.member?(event_id_set, relationship["ocel:event"])
        assert MapSet.member?(object_id_set, relationship["ocel:object"])
      end)

      [first_receipt] = Receipt.read_all!(work_dir)
      assert first_receipt["standing"] == "alive"
      assert output_path in first_receipt["files"]
      assert first_receipt["metadata"]["graph_hash"] == sha256_file(@ontology_path)

      {second_output, second_exit} =
        run_sync(work_dir, [], "semantic-jira-pack:ocel", "", "ocel.json")

      assert second_exit == 0, "second OCEL sync failed:\n#{second_output}"
      assert File.read!(output_path) == first_bytes

      receipts = Receipt.read_all!(work_dir)
      assert length(receipts) == 2

      [first_graph_hash, second_graph_hash] =
        Enum.map(receipts, &get_in(&1, ["metadata", "graph_hash"]))

      assert first_graph_hash == second_graph_hash
      assert second_graph_hash == sha256_file(@ontology_path)
    end

    test "removing a required baseSha refuses the OCEL projection before any file is written" do
      work_dir = scratch_dir!("ocel_missing_base_sha")
      broken_ontology = Path.join(work_dir, "missing-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/^    sj:baseSha "[0-9a-f]+" ;\n/m,
          "",
          global: false
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(
          work_dir,
          ["--ontology", broken_ontology],
          "semantic-jira-pack:ocel",
          "",
          "ocel.json"
        )

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing core field base_sha"
      refute File.exists?(Path.join(work_dir, "ocel.json"))

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end

  describe "ARD projection template" do
    test "manufactures the ARD decision records for the dogfood set and replays byte-identically" do
      work_dir = scratch_dir!("ard_projection")
      output_path = Path.join(work_dir, "SJ-001.ard.md")

      {first_output, first_exit} =
        run_sync(work_dir, [], "semantic-jira-pack:ard", ".ard.md")

      assert first_exit == 0, "first ARD sync failed:\n#{first_output}"
      assert File.exists?(output_path)
      assert File.exists?(Path.join(work_dir, "GALL-001.ard.md"))
      assert File.exists?(Path.join(work_dir, "GALL-032.ard.md"))
      assert length(Path.wildcard(Path.join(work_dir, "*.ard.md"))) == 33

      first_bytes = File.read!(output_path)

      assert first_bytes =~
               "<!-- GENERATED by semantic-jira-pack from canonical RDF WorkOrder"

      assert first_bytes =~ "# ARD: SJ-001 — Manufacture Semantic Jira work orders from RDF"
      assert first_bytes =~ "**Base SHA:** d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3"
      assert first_bytes =~ "**Standing:** UNKNOWN"
      assert first_bytes =~ "**Exact subject:** semantic-jira-pack:work-order-projection"
      assert first_bytes =~ "**Authority ceiling:** CONSTRUCT"
      assert first_bytes =~ "**Evidence ceiling:** IMPLEMENTED_UNVERIFIED"
      assert first_bytes =~ "zero independent actuation"

      # Decision/Consequences/Verification framing, all values graph-derived.
      assert first_bytes =~ "## Decision D-1: the boundary"
      assert first_bytes =~ "## Decision D-2: authority"
      assert first_bytes =~ "## Decision D-3: promotion"
      assert first_bytes =~ "## Decision D-4: falsifiability"
      assert first_bytes =~ "**Decision:**"
      assert first_bytes =~ "**Consequences:**"
      assert first_bytes =~ "**Verification:**"

      # D-1 boundary: path scope and replay identity come from the graph.
      assert first_bytes =~ "priv/ggen/semantic-jira-pack"
      assert first_bytes =~ "semantic-jira:v26.9.19:SJ-001"

      # D-2 authority: requirement NONE and receipt classes from the graph.
      assert first_bytes =~ "- NONE"
      assert first_bytes =~ "- manufacture"
      assert first_bytes =~ "- projection"

      # D-3 promotion: the promotion rule and its courts/evidence nodes.
      assert first_bytes =~
               "Standing may advance only from an independent exact-head court receipt"

      assert first_bytes =~ "Exact-head Semantic Jira projection court"
      assert first_bytes =~ "Graph-bound receipt"

      # D-4 falsifiability: falsifier and acceptance nodes from the graph.
      assert first_bytes =~ "Missing required field still renders"
      assert first_bytes =~ "Projection gains authority"
      assert first_bytes =~ "Canonical RDF source"
      assert first_bytes =~ "Deterministic projection"

      refute first_bytes =~ "TODO"
      refute first_bytes =~ "PLACEHOLDER"

      [first_receipt] = Receipt.read_all!(work_dir)
      assert first_receipt["standing"] == "alive"
      assert output_path in first_receipt["files"]
      assert first_receipt["metadata"]["graph_hash"] == sha256_file(@ontology_path)

      {second_output, second_exit} =
        run_sync(work_dir, [], "semantic-jira-pack:ard", ".ard.md")

      assert second_exit == 0, "second ARD sync failed:\n#{second_output}"
      assert File.read!(output_path) == first_bytes

      receipts = Receipt.read_all!(work_dir)
      assert length(receipts) == 2

      [first_graph_hash, second_graph_hash] =
        Enum.map(receipts, &get_in(&1, ["metadata", "graph_hash"]))

      assert first_graph_hash == second_graph_hash
      assert second_graph_hash == sha256_file(@ontology_path)
    end

    test "removing a required baseSha refuses the ARD projection before any file is actuated" do
      work_dir = scratch_dir!("ard_missing_base_sha")
      broken_ontology = Path.join(work_dir, "missing-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/^    sj:baseSha "[0-9a-f]+" ;\n/m,
          "",
          global: false
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, ["--ontology", broken_ontology], "semantic-jira-pack:ard", ".ard.md")

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing core field base_sha"
      refute File.exists?(Path.join(work_dir, "SJ-001.ard.md"))

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end

  describe "semantic admission falsifier" do
    test "removing a required baseSha refuses before any ticket is actuated" do
      work_dir = scratch_dir!("missing_base_sha")
      broken_ontology = Path.join(work_dir, "missing-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/^    sj:baseSha "[0-9a-f]+" ;\n/m,
          "",
          global: false
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, [
          "--ontology",
          broken_ontology
        ])

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing core field base_sha"
      refute File.exists?(Path.join(work_dir, "SJ-001.md"))

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end

  describe "graph-binding tripwires" do
    test "every pack gate executes cleanly against the canonical graph" do
      graph = GgenIgniter.Ontology.load!(@ontology_path)

      gates =
        "priv/ggen/semantic-jira-pack/gates/*.rq"
        |> Path.wildcard()
        |> Enum.sort()

      assert length(gates) == 7

      Enum.each(gates, fn gate ->
        assert is_list(GgenIgniter.Query.run(graph, File.read!(gate))),
               "gate #{Path.basename(gate)} does not execute against the canonical graph"
      end)

      # The self-dogfood WorkOrder has no dependency edges, so the frontier
      # gate (nested MINUS, not FILTER NOT EXISTS — see 050_frontier.rq) must
      # keep it eligible; an inverted or crashing frontier loses it.
      frontier_rows =
        graph
        |> GgenIgniter.Query.run(File.read!("priv/ggen/semantic-jira-pack/gates/050_frontier.rq"))

      frontier_ids = Enum.map(frontier_rows, & &1["id"])

      assert "SJ-001" in frontier_ids
      refute frontier_ids == []
    end

    test "mutating a scalar fact in the graph changes the projection" do
      work_dir = scratch_dir!("scalar_mutation")
      mutated_ontology = Path.join(work_dir, "mutated-title.ttl")

      old_title = "Manufacture Semantic Jira work orders from RDF"
      new_title = "Manufacture Semantic Jira work orders from canonical RDF"

      source = File.read!(@ontology_path)
      mutated = String.replace(source, old_title, new_title)

      refute mutated == source
      File.write!(mutated_ontology, mutated)

      {output, exit_code} = run_sync(work_dir, ["--ontology", mutated_ontology])

      assert exit_code == 0, "mutated-graph sync failed:\n#{output}"

      projected = File.read!(Path.join(work_dir, "SJ-001.md"))
      assert projected =~ new_title
      refute projected =~ old_title
    end

    test "deleting a required relation refuses before any ticket is actuated" do
      work_dir = scratch_dir!("missing_relation")
      broken_ontology = Path.join(work_dir, "missing-requires-court.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          "sj:requiresCourt sj:exact-head-projection-court",
          "sj:requiresCourtX sj:exact-head-projection-court"
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, [
          "--ontology",
          broken_ontology
        ])

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing required requiresCourt relation for SJ-001"
      assert Path.wildcard(Path.join(work_dir, "*.md")) == []

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end

    test "corrupting baseSha to a non-SHA scalar refuses before any ticket is actuated" do
      work_dir = scratch_dir!("corrupt_base_sha")
      broken_ontology = Path.join(work_dir, "corrupt-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/sj:baseSha "[0-9a-f]{40}"/,
          ~s{sj:baseSha "main"},
          global: true
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, [
          "--ontology",
          broken_ontology
        ])

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "baseSha must be an exact 40-hex commit SHA"
      assert Path.wildcard(Path.join(work_dir, "*.md")) == []

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end

  describe "admission boundary falsifier matrix" do
    # One test per attack, named after the rejection class it witnesses. Every
    # attack mutates a copy of the canonical dogfood graph and drives the REAL
    # admission path (mix ggen_igniter.sync --engine sparql --pack
    # semantic-jira-pack:jira --ontology <mutated>): no simulated admissions.
    #
    # LAW CHANGE (v26.9.19, residual closure): the class-3 exact-baseSha
    # refusals below remain the DEFAULT law and are NOT weakened. The residual
    # this matrix witnessed -- `residual_base_sha_wrong_commit`, a format-valid
    # 40-hex SHA that is not a real commit -- is now closed by OPT-IN git
    # ground truth (`GgenIgniter.SemanticJira.GitGroundTruth`, the sync task's
    # `--verify-base-sha` flag, and the per-order `sj:requiresGitGroundTruth`
    # refinement). That ADDED law is proven in both directions by the
    # "opt-in git ground truth for baseSha" describe block below.

    @dogfood_title ~s(dcterms:title "Manufacture Semantic Jira work orders from RDF" ;)
    @dogfood_identifier ~s(dcterms:identifier "SJ-001" ;)
    @dogfood_base_sha ~s(sj:baseSha "d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3" ;)
    @dogfood_standing ~s(sj:standing "UNKNOWN" ;)
    @dogfood_authority ~s(sj:authorityCeiling "CONSTRUCT" ;)
    @dogfood_replay ~s(sj:replayIdentity "semantic-jira:v26.9.19:SJ-001" ;)
    # The dogfood WorkOrder block ends with this final triple; appended attack
    # subjects go after the terminator.
    @dogfood_close "sj:nextCheckpoint sj:shacl-admission-checkpoint ."

    test "class 1 incomplete scalar identity: removing dcterms:title refuses admission" do
      assert_refused("class1_missing_title", [{@dogfood_title, ""}], "missing core field title")
    end

    test "class 1 incomplete scalar identity: removing dcterms:identifier refuses admission" do
      assert_refused(
        "class1_missing_identifier",
        [{@dogfood_identifier, ""}],
        "missing core field id"
      )
    end

    test "class 1 ambiguous scalar identity: a duplicated dcterms:title resolves to two rows and refuses" do
      assert_refused(
        "class1_ambiguous_title",
        [{@dogfood_title, @dogfood_title <> ~s(\n    dcterms:title "Shadow title" ;)}],
        "exactly one complete scalar row"
      )
    end

    test "class 1 ambiguous scalar identity: a duplicated sj:baseSha resolves to two rows and refuses" do
      assert_refused(
        "class1_ambiguous_base_sha",
        [
          {@dogfood_base_sha,
           @dogfood_base_sha <> ~s(\n    sj:baseSha "#{String.duplicate("a", 40)}" ;)}
        ],
        "exactly one complete scalar row"
      )
    end

    test "class 2 duplicate identity: a second WorkOrder reusing dcterms:identifier SJ-001 refuses" do
      assert_refused(
        "class2_duplicate_id",
        [
          {@dogfood_close,
           @dogfood_close <>
             attack_work_order("SJ-001", "semantic-jira:v26.9.19:ATTACK-DUP", "dup")}
        ],
        "dcterms:identifier must be unique across WorkOrders"
      )
    end

    test "class 2 duplicate identity: two individually valid WorkOrders sharing one identifier refuse (combinational bypass)" do
      # Each added WorkOrder is individually legal (complete and well-formed);
      # only the combination - a shared identifier - is illegal.
      assert_refused(
        "class2_combo_duplicate_id",
        [
          {@dogfood_close,
           @dogfood_close <>
             attack_work_order("SJ-COMBO", "semantic-jira:v26.9.19:ATTACK-COMBO-A", "combo-a") <>
             attack_work_order("SJ-COMBO", "semantic-jira:v26.9.19:ATTACK-COMBO-B", "combo-b")}
        ],
        "dcterms:identifier must be unique across WorkOrders"
      )
    end

    test "class 3 exact baseSha: uppercase hex refuses (exact means exact)" do
      assert_refused(
        "class3_base_sha_uppercase",
        [{@dogfood_base_sha, ~s(sj:baseSha "D84DA1419A6945C6A8A64B8F6CDCA9D0B2C9E0F3" ;)}],
        "baseSha must be an exact 40-hex commit SHA"
      )
    end

    test "class 3 exact baseSha: truncated 39-hex refuses" do
      assert_refused(
        "class3_base_sha_truncated",
        [{@dogfood_base_sha, ~s(sj:baseSha "#{String.duplicate("d", 39)}" ;)}],
        "baseSha must be an exact 40-hex commit SHA"
      )
    end

    test "class 3 exact baseSha: extended 41-hex refuses" do
      assert_refused(
        "class3_base_sha_extended",
        [{@dogfood_base_sha, ~s(sj:baseSha "#{String.duplicate("d", 41)}" ;)}],
        "baseSha must be an exact 40-hex commit SHA"
      )
    end

    test "class 3 exact baseSha: leading whitespace refuses (identity smuggling)" do
      assert_refused(
        "class3_base_sha_whitespace",
        [{@dogfood_base_sha, ~s(sj:baseSha " #{String.duplicate("d", 40)}" ;)}],
        "baseSha must be an exact 40-hex commit SHA"
      )
    end

    test "class 4 standing vocabulary: lowercase and fabricated standings refuse" do
      assert_refused(
        "class4_standing_lowercase",
        [{@dogfood_standing, ~s(sj:standing "unknown" ;)}],
        "invalid standing"
      )

      assert_refused(
        "class4_standing_fabricated",
        [{@dogfood_standing, ~s(sj:standing "SUPER_ALIVE" ;)}],
        "invalid standing"
      )
    end

    test "class 4 standing vocabulary: REFUSED() with an empty reason refuses (a refusal must state its reason)" do
      refused_empty_standing = "sj:standing \"REFUSED()\" ;"
      # The sync output surfaces refusals through an ArgumentError inspect,
      # which escapes quotes; match on the quote-free signal prefix.
      refused_empty_signal = "invalid standing"

      assert_refused(
        "class4_standing_refused_empty",
        [{@dogfood_standing, refused_empty_standing}],
        refused_empty_signal
      )
    end

    test "class 5 authority ceiling: MERGE and DEPLOY refuse above the CONSTRUCT boundary" do
      assert_refused(
        "class5_authority_merge",
        [{@dogfood_authority, ~s(sj:authorityCeiling "MERGE" ;)}],
        "exceeds Semantic Jira's OBSERVE/SELECT/CONSTRUCT boundary"
      )

      assert_refused(
        "class5_authority_deploy",
        [{@dogfood_authority, ~s(sj:authorityCeiling "DEPLOY" ;)}],
        "exceeds Semantic Jira's OBSERVE/SELECT/CONSTRUCT boundary"
      )
    end

    test "class 5 authority ceiling: CONSTRUCT typos and trailing whitespace refuse" do
      assert_refused(
        "class5_authority_typo",
        [{@dogfood_authority, ~s(sj:authorityCeiling "constrct" ;)}],
        "exceeds Semantic Jira's OBSERVE/SELECT/CONSTRUCT boundary"
      )

      assert_refused(
        "class5_authority_trailing_space",
        [{@dogfood_authority, ~s(sj:authorityCeiling "CONSTRUCT " ;)}],
        "exceeds Semantic Jira's OBSERVE/SELECT/CONSTRUCT boundary"
      )
    end

    test "class 5 authority ceiling control: OBSERVE stays inside the boundary and admits" do
      assert_admitted("class5_control_observe", [
        {@dogfood_authority, ~s(sj:authorityCeiling "OBSERVE" ;)}
      ])
    end

    for relation <-
          ~w(requiresCourt requiresEvidence acceptance falsifier projection nextAction nextCheckpoint) do
      test "class 6 required relation: a graph without sj:#{relation} on SJ-001 refuses" do
        assert_refused(
          "class6_missing_#{unquote(relation)}",
          remove_relation_mutations(unquote(relation)),
          "missing required #{unquote(relation)} relation for SJ-001"
        )
      end
    end

    test "class 7 relation target: a target carrying only rdfs:label refuses" do
      assert_refused(
        "class7_target_label_only",
        [
          {dogfood_falsifier_statement(), ~s(sj:falsifier sj:label-only-target ;)},
          {@dogfood_close,
           @dogfood_close <>
             ~s(\nsj:label-only-target a sj:Falsifier ; rdfs:label "Label only target" .\n)}
        ],
        "lacks rdfs:label + dcterms:description"
      )
    end

    test "class 7 relation target: a bare IRI target with no label or description refuses" do
      assert_refused(
        "class7_target_bare_iri",
        [{dogfood_falsifier_statement(), ~s(sj:falsifier sj:bare-target ;)}],
        "lacks rdfs:label + dcterms:description"
      )
    end

    test "class 7 relation target: a plain literal target refuses" do
      assert_refused(
        "class7_target_literal",
        [
          {~s(sj:nextAction sj:add-qualified-shacl-court ;),
           ~s(sj:nextAction sj:add-qualified-shacl-court, "just do it" ;)}
        ],
        "for SJ-001 lacks rdfs:label + dcterms:description"
      )
    end

    test "standing smuggling: ALIVE without candidateSha, subjectSha, and receipt refuses (SHACL receipt-crown law)" do
      # shapes/work-order.shacl.ttl: "ALIVE requires exact candidate/subject SHA
      # and a durable receipt." A graph claiming the strongest standing with
      # zero observed-execution evidence must not admit.
      assert_refused(
        "extra_alive_without_receipt_crown",
        [{@dogfood_standing, ~s(sj:standing "ALIVE" ;)}],
        "standing ALIVE requires sj:candidateSha, sj:subjectSha, and sj:receipt evidence"
      )
    end

    test "standing smuggling control: ALIVE with the full receipt crown admits" do
      crown =
        ~s(sj:standing "ALIVE" ;\n    sj:candidateSha "#{String.duplicate("c", 40)}" ;\n    sj:subjectSha "#{String.duplicate("d", 40)}" ;\n    sj:receipt sj:graph-receipt-evidence ;)

      assert_admitted("extra_control_alive_with_receipt_crown", [{@dogfood_standing, crown}])
    end

    test "replay identity uniqueness: two valid WorkOrders sharing sj:replayIdentity refuse (SHACL uniqueness law)" do
      assert_refused(
        "extra_duplicate_replay_identity",
        [
          {@dogfood_close,
           @dogfood_close <>
             attack_work_order("SJ-REPL-A", "semantic-jira:v26.9.19:ATTACK-SHARED", "repl-a") <>
             attack_work_order("SJ-REPL-B", "semantic-jira:v26.9.19:ATTACK-SHARED", "repl-b")}
        ],
        "sj:replayIdentity must be unique across WorkOrders"
      )
    end

    test "description integrity: an empty-string description on a relation target refuses (no blank semantics)" do
      assert_refused(
        "extra_empty_description_target",
        [
          {dogfood_falsifier_statement(), ~s(sj:falsifier sj:empty-desc-target ;)},
          {@dogfood_close,
           @dogfood_close <>
             ~s(\nsj:empty-desc-target a sj:Falsifier ; rdfs:label "Empty description target" ; dcterms:description "" .\n)}
        ],
        "lacks a real description"
      )
    end

    test "description integrity: a whitespace-only description refuses" do
      assert_refused(
        "extra_whitespace_description_target",
        [
          {dogfood_falsifier_statement(), ~s(sj:falsifier sj:ws-desc-target ;)},
          {@dogfood_close,
           @dogfood_close <>
             ~s(\nsj:ws-desc-target a sj:Falsifier ; rdfs:label "Whitespace description target" ; dcterms:description "   " .\n)}
        ],
        "blank or whitespace-only"
      )
    end

    test "description integrity: a description echoing the node IRI refuses (self-reference is not semantics)" do
      assert_refused(
        "extra_self_echo_description_target",
        [
          {dogfood_falsifier_statement(), ~s(sj:falsifier sj:echo-desc-target ;)},
          {@dogfood_close,
           @dogfood_close <>
             ~s(\nsj:echo-desc-target a sj:Falsifier ; rdfs:label "Echo description target" ; dcterms:description "https://ggen-igniter.dev/ontology/semantic-jira#echo-desc-target" .\n)}
        ],
        "lacks a real description"
      )
    end

    test "description integrity: a description equal to the node label refuses" do
      assert_refused(
        "extra_description_equals_label_target",
        [
          {dogfood_falsifier_statement(), ~s(sj:falsifier sj:same-desc-target ;)},
          {@dogfood_close,
           @dogfood_close <>
             ~s(\nsj:same-desc-target a sj:Falsifier ; rdfs:label "Same description target" ; dcterms:description "Same description target" .\n)}
        ],
        "lacks a real description"
      )
    end

    test "scalar identity: a whitespace-only title refuses (whitespace is not identity)" do
      assert_refused(
        "extra_whitespace_title",
        [{@dogfood_title, ~s(dcterms:title "   " ;)}],
        "blank core field title"
      )
    end

    test "scalar identity: a whitespace-only replayIdentity refuses" do
      assert_refused(
        "extra_whitespace_replay_identity",
        [{@dogfood_replay, ~s(sj:replayIdentity "   " ;)}],
        "blank core field replay_identity"
      )
    end

    test "malformed ontology: a Turtle syntax error fails closed with no ticket actuated" do
      work_dir = scratch_dir!("malformed_turtle")

      mutated =
        mutate_ontology!(work_dir, "malformed", [
          {@dogfood_title, ~s(dcterms:title "Unclosed title ;)}
        ])

      {output, exit_code} = run_sync(work_dir, ["--ontology", mutated])

      refute exit_code == 0
      refute output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      refute File.exists?(Path.join(work_dir, "SJ-001.md"))
      assert output =~ "Turtle"
    end
  end

  describe "opt-in git ground truth for baseSha (residual_base_sha_wrong_commit closure)" do
    # Drives the REAL CLI (no simulated git): the run's --verify-cwd default
    # is File.cwd!() -- this clone -- whose history contains the canonical
    # baseSha d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3 as a real commit
    # reachable from HEAD (witnessed before these tests existed:
    # `git cat-file -e d84da141...^{commit}` -> 0 and
    # `git merge-base --is-ancestor d84da141... HEAD` -> 0).

    test "flag on over the honest graph manufactures (honest-pass side)" do
      work_dir = scratch_dir!("git_truth_honest")

      {output, exit_code} = run_sync(work_dir, ["--verify-base-sha"])

      assert exit_code == 0, "git-ground-truth honest sync failed:\n#{output}"
      assert File.exists?(Path.join(work_dir, "SJ-001.md"))
      assert File.exists?(Path.join(work_dir, "GALL-001.md"))
      assert File.exists?(Path.join(work_dir, "GALL-032.md"))
      assert length(Path.wildcard(Path.join(work_dir, "*.md"))) == 33
    end

    test "flag on over a forged-but-well-formed 40-hex baseSha refuses before any actuation" do
      work_dir = scratch_dir!("git_truth_forged")

      mutated =
        mutate_ontology!(work_dir, "git-truth-forged", [
          # Format-valid (40-hex) but not a commit in any checkout: exactly
          # the residual_base_sha_wrong_commit attack shape.
          {@dogfood_base_sha, ~s(sj:baseSha "#{String.duplicate("d", 40)}" ;)}
        ])

      {output, exit_code} = run_sync(work_dir, ["--ontology", mutated, "--verify-base-sha"])

      refute exit_code == 0, "expected git-ground-truth refusal, got exit 0:\n#{output}"
      assert output =~ "REFUSED:SEMANTIC_JIRA_BASE_SHA_UNVERIFIED"
      assert output =~ "baseSha #{String.duplicate("d", 40)} is not a commit reachable in"
      assert Path.wildcard(Path.join(work_dir, "*.md")) == []

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end

    test "flag off keeps current behavior: the honest graph still manufactures (no-regression falsifier)" do
      work_dir = scratch_dir!("git_truth_flag_off")

      {output, exit_code} = run_sync(work_dir)

      assert exit_code == 0, "flag-off honest sync failed:\n#{output}"
      assert length(Path.wildcard(Path.join(work_dir, "*.md"))) == 33
    end

    test "flag on with a non-git --verify-cwd refuses cleanly, not a crash" do
      work_dir = scratch_dir!("git_truth_non_git")

      # A plain scratch dir: no .git anywhere up its tree. The later
      # --verify-cwd flag wins over run_sync's own default.
      {output, exit_code} =
        run_sync(work_dir, ["--verify-base-sha", "--verify-cwd", work_dir])

      refute exit_code == 0, "expected non-git refusal, got exit 0:\n#{output}"
      assert output =~ "REFUSED:SEMANTIC_JIRA_BASE_SHA_UNVERIFIED"
      assert output =~ "#{work_dir} is not a git work tree"
      assert Path.wildcard(Path.join(work_dir, "*.md")) == []

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end

    test "per-order sj:requiresGitGroundTruth true verifies that order without the flag" do
      work_dir = scratch_dir!("git_truth_predicate")

      mutated =
        mutate_ontology!(work_dir, "git-truth-predicate", [
          {@dogfood_base_sha,
           ~s(sj:baseSha "#{String.duplicate("d", 40)}" ;\n    sj:requiresGitGroundTruth true ;)}
        ])

      # No --verify-base-sha flag: only the order that opted itself in is
      # git-verified, and its forged baseSha refuses.
      {output, exit_code} = run_sync(work_dir, ["--ontology", mutated])

      refute exit_code == 0, "expected per-order git-ground-truth refusal, got exit 0:\n#{output}"
      assert output =~ "REFUSED:SEMANTIC_JIRA_BASE_SHA_UNVERIFIED"
      assert Path.wildcard(Path.join(work_dir, "*.md")) == []
    end

    test "per-order control: requiresGitGroundTruth true over a real ancestor admits without the flag" do
      work_dir = scratch_dir!("git_truth_predicate_ok")

      mutated =
        mutate_ontology!(work_dir, "git-truth-predicate-ok", [
          {@dogfood_base_sha, @dogfood_base_sha <> ~s(\n    sj:requiresGitGroundTruth true ;)}
        ])

      {output, exit_code} = run_sync(work_dir, ["--ontology", mutated])

      assert exit_code == 0, "per-order git-ground-truth control failed:\n#{output}"
      assert File.exists?(Path.join(work_dir, "SJ-001.md"))
      assert length(Path.wildcard(Path.join(work_dir, "*.md"))) == 33
    end
  end

  defp dogfood_falsifier_statement do
    "sj:falsifier sj:missing-required-field-renders, sj:projection-gains-authority ;"
  end

  defp attack_work_order(identifier, replay_identity, suffix) do
    """
    sj:attack-#{suffix} a sj:WorkOrder ;
        dcterms:identifier "#{identifier}" ;
        dcterms:title "Attack work order #{identifier}" ;
        dcterms:description "Attack row reusing canonical relation targets." ;
        sj:repository "seanchatmangpt/ggen_igniter" ;
        sj:baseSha "d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3" ;
        sj:subject "semantic-jira-pack:attack-#{suffix}" ;
        sj:standing "UNKNOWN" ;
        sj:evidenceCeiling "IMPLEMENTED_UNVERIFIED" ;
        sj:authorityCeiling "CONSTRUCT" ;
        sj:promotionRule "Attack row; admission must refuse." ;
        sj:replayIdentity "#{replay_identity}" ;
        sj:requiresCourt sj:exact-head-projection-court ;
        sj:requiresEvidence sj:graph-receipt-evidence ;
        sj:acceptance sj:canonical-source ;
        sj:falsifier sj:missing-required-field-renders ;
        sj:projection sj:markdown-projection ;
        sj:nextAction sj:add-qualified-shacl-court ;
        sj:nextCheckpoint sj:shacl-admission-checkpoint .
    """
  end

  # SJ-001 carries its dogfood relations and (in the v26.9.19 fabric block) a
  # second sj:projection statement with the fourteen ProjectionSpecs; removing
  # only one statement leaves the graph untouched from the graph's point of
  # view, so both must go. The nextCheckpoint triple terminates the subject,
  # so dropping it keeps the "." terminator.
  defp remove_relation_mutations("projection") do
    [
      {"sj:projection sj:markdown-projection ;\n", ""},
      {"sj:projection sj:projection-jira, sj:projection-wbpr, sj:projection-prd, sj:projection-ard, sj:projection-vision, sj:projection-fond, sj:projection-hddl, sj:projection-sa2a, sj:projection-worker, sj:projection-verification, sj:projection-executive, sj:projection-machine, sj:projection-receipt, sj:projection-replay .",
       "."}
    ]
  end

  defp remove_relation_mutations("nextCheckpoint") do
    [{"sj:nextCheckpoint sj:shacl-admission-checkpoint .", "."}]
  end

  defp remove_relation_mutations(relation) do
    relation_iri =
      case relation do
        "requiresCourt" ->
          "sj:requiresCourt sj:exact-head-projection-court ;"

        "requiresEvidence" ->
          "sj:requiresEvidence sj:graph-receipt-evidence ;"

        "acceptance" ->
          "sj:acceptance sj:canonical-source, sj:deterministic-projection, sj:fail-closed-invalid ;"

        "falsifier" ->
          dogfood_falsifier_statement()

        "nextAction" ->
          "sj:nextAction sj:add-qualified-shacl-court ;"
      end

    [{relation_iri, ""}]
  end

  defp mutate_ontology!(work_dir, tag, replacements) do
    path = Path.join(work_dir, "#{tag}.ttl")

    mutated =
      Enum.reduce(replacements, File.read!(@ontology_path), fn {find, replace}, acc ->
        String.replace(acc, find, replace, global: false)
      end)

    # Every mutation must actually change the graph; a no-op mutation would
    # fabricate a rejection signal.
    refute mutated == File.read!(@ontology_path)
    File.write!(path, mutated)
    path
  end

  defp assert_refused(tag, replacements, expected_signal) do
    work_dir = scratch_dir!(tag)
    mutated = mutate_ontology!(work_dir, tag, replacements)
    {output, exit_code} = run_sync(work_dir, ["--ontology", mutated])

    refute exit_code == 0, "expected refusal, got exit 0:\n#{output}"
    assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
    assert output =~ expected_signal
    refute File.exists?(Path.join(work_dir, "SJ-001.md"))

    receipts = Receipt.read_all!(work_dir)

    assert Enum.all?(receipts, fn receipt ->
             receipt["standing"] != "alive"
           end)
  end

  defp assert_admitted(tag, replacements) do
    work_dir = scratch_dir!(tag)
    mutated = mutate_ontology!(work_dir, tag, replacements)
    {output, exit_code} = run_sync(work_dir, ["--ontology", mutated])

    assert exit_code == 0, "expected admission, got exit #{exit_code}:\n#{output}"
    assert File.exists?(Path.join(work_dir, "SJ-001.md"))
  end

  defp semantic_digest(seed), do: "sha256:" <> String.duplicate(seed, 64)

  defp sample_work_order(overrides \\ %{}) do
    Map.merge(
      %{
        "identity" => "SJ-TEST-001",
        "title" => "Bounded semantic test",
        "description" => "Exercise the kernel without granting authority.",
        "subject" => "urn:subject:test",
        "repository" => "seanchatmangpt/ggen_igniter",
        "base_sha" => String.duplicate("a", 40),
        "standing" => "UNKNOWN",
        "evidence_ceiling" => "repository-local",
        "promotion_rule" => "exact subject and independent evidence",
        "replay_identity" => "semantic-jira:test:1",
        "dependencies" => [],
        "required_courts" => ["court:test"],
        "required_evidence" => ["source", "verification"],
        "acceptance" => ["acceptance:test"],
        "falsifiers" => ["falsifier:test"],
        "projections" => SemanticJira.projection_types(),
        "required_receipt_classes" => ["verification"],
        "path_scope" => ["lib/ggen_igniter"],
        "authority_requirement" => "NONE",
        "replay_required" => false
      },
      overrides
    )
  end

  describe "DfCM semantic kernel" do
    test "admission, frontier, scheduling, lease requests, and worker packages preserve boundaries" do
      work_order = sample_work_order()
      reversed = work_order |> Enum.reverse() |> Map.new()

      {:ok, first} = SemanticJira.admit_work_order(work_order)
      {:ok, second} = SemanticJira.admit_work_order(reversed)
      assert first["work_order_digest"] == second["work_order_digest"]
      assert first["authority"] == "NONE"

      # Kernel refusals are uniformly wrapped in the typed refusal vocabulary
      # (the non-map clause returns {:refused_work_order, :expected_map} too).
      assert {:error, {:refused_work_order, {:invalid_sha, :base_sha, "main"}}} =
               SemanticJira.admit_work_order(%{work_order | "base_sha" => "main"})

      dependent =
        sample_work_order(%{
          "identity" => "DOWNSTREAM",
          "dependencies" => [
            %{
              "upstream" => "UPSTREAM",
              "type" => "requiresReceipt",
              "required_standing" => "ALIVE",
              "required_receipt_digest" => semantic_digest("b")
            }
          ]
        })

      evidence = %{
        "UPSTREAM" => %{
          "standing" => "ALIVE",
          "receipt_digest" => semantic_digest("b")
        }
      }

      assert [%{"identity" => "DOWNSTREAM", "authority" => "NONE"}] =
               SemanticJira.frontier([dependent], evidence).eligible

      scheduled =
        SemanticJira.schedule(
          [dependent],
          [
            %{
              "status" => "active",
              "repository" => "seanchatmangpt/ggen_igniter",
              "scope" => ["lib/ggen_igniter/semantic_jira.ex"]
            }
          ],
          evidence
        )

      assert scheduled.eligible == []
      assert Enum.any?(scheduled.blocked, &(&1["reason"] == "conflicting_active_lease"))

      lease_attrs = %{
        "run_id" => "run-1",
        "epoch_id" => "epoch-1",
        "worker_identity" => "zcode-cli:worker-7",
        "scope" => ["lib/ggen_igniter/semantic_jira.ex"],
        "allowed_operations" => ["read", "edit", "test"],
        "expiration" => "2026-09-20T00:00:00Z",
        "concurrency_key" => "ggen_igniter:semantic-jira"
      }

      assert {:ok, request} = SemanticJira.lease_request(work_order, lease_attrs)
      assert request["owner"] == "XaaS/Ultracode"
      assert request["authority"] == "NONE"

      assert {:ok, package} =
               SemanticJira.execution_package(work_order, %{
                 "graph_digest" => semantic_digest("c"),
                 "source_digest" => semantic_digest("d"),
                 "worker_identity" => "zcode-cli:worker-7",
                 "verifier_identity" => "court:independent-1"
               })

      assert package.subject_id == "urn:subject:test"
      assert hd(package.actions)["authority"] == "NONE"
    end

    test "DO intent fails closed on claim-store error and crash windows stay explicit" do
      work_order = sample_work_order(%{"authority_requirement" => "repo-write"})
      {:ok, admitted} = SemanticJira.admit_work_order(work_order)

      authority = %{
        "status" => "prepared",
        "work_order_digest" => admitted["work_order_digest"],
        "subject" => admitted["subject"],
        "replay_identity" => admitted["replay_identity"],
        "authority_identity" => "authority:1"
      }

      attrs = %{
        "claim_store_status" => "error",
        "prepared_authority_receipt" => authority,
        "lease_id" => "lease:1",
        "capability_identity" => "capability:test",
        "command_identity" => "command:test"
      }

      assert {:error, {:refused_do, :claim_store_unavailable}} =
               SemanticJira.do_intent(work_order, attrs)

      assert {:ok, intent} =
               SemanticJira.do_intent(
                 work_order,
                 %{attrs | "claim_store_status" => "available"}
               )

      assert intent["executed"] == false
      assert intent["owner"] == "BRCE/CommandBus"

      assert {:ok, %{"reconciliation_state" => "EFFECT_OBSERVED_RECEIPT_MISSING"}} =
               SemanticJira.reconcile_crash_window(%{
                 "effect_identity" => "effect:1",
                 "claim_state" => "committed",
                 "consequence_observed" => true,
                 "receipt_state" => "absent"
               })
    end

    test "verification, promotion, MachineExperience, composition, and replay require exact evidence" do
      {:ok, work_order} = SemanticJira.admit_work_order(sample_work_order())

      assert {:ok, verification} =
               SemanticJira.exact_head_verification_evidence(%{
                 "repository" => work_order["repository"],
                 "base_sha" => work_order["base_sha"],
                 "candidate_sha" => String.duplicate("b", 40),
                 "work_order_digest" => work_order["work_order_digest"],
                 "projection_digest" => semantic_digest("d"),
                 "command" => "mix test",
                 "exit_code" => 0,
                 "toolchain_identity" => "elixir:1.18.4-otp-27",
                 "environment_identity" => "ubuntu:hosted",
                 "validator_identity" => "court:test",
                 "test_result_digest" => semantic_digest("e"),
                 "falsifier_results" => [
                   %{"name" => "identity", "verdict" => "survived"}
                 ]
               })

      assert verification["passed"] == true
      assert verification["standing_authority"] == "NONE"

      evidence = %{
        "work_order_digest" => work_order["work_order_digest"],
        "subject" => work_order["subject"],
        "repository" => work_order["repository"],
        "base_sha" => work_order["base_sha"],
        "dependency_evidence" => %{},
        "court_results" => %{"court:test" => %{"passed" => true}},
        "evidence_types" => ["source", "verification"],
        "acceptance_results" => %{"acceptance:test" => true},
        "falsifier_results" => %{"falsifier:test" => "survived"},
        "receipt_classes" => ["verification"],
        "evidence_ceiling" => work_order["evidence_ceiling"],
        "observed_execution" => true,
        "inherited_standing" => false
      }

      assert {:ok, transition} =
               SemanticJira.promote(work_order, "ALIVE", evidence)

      assert transition["authority"] == "NONE"

      assert {:error, {:promotion_refused, failed}} =
               SemanticJira.promote(
                 work_order,
                 "ALIVE",
                 %{evidence | "inherited_standing" => true}
               )

      assert :no_inherited_crown in failed

      experience_attrs = %{
        "subject" => work_order["subject"],
        "work_order_digest" => work_order["work_order_digest"],
        "execution_receipt" => %{
          "executed" => true,
          "receipt_hash" => semantic_digest("a")
        },
        "observation_refs" => ["ocel:event:1"],
        "verification" => %{"passed" => true},
        "resulting_state" => %{"digest" => semantic_digest("b")},
        "replay_identity" => work_order["replay_identity"]
      }

      assert {:ok, experience} =
               SemanticJira.machine_experience(experience_attrs)

      assert experience["standing"] == "CANDIDATE"

      assert {:error, {:refused_machine_experience, :prediction_only}} =
               SemanticJira.machine_experience(Map.put(experience_attrs, "prediction_only", true))

      assert {:ok, composition} =
               SemanticJira.composition_subject([
                 %{
                   "work_order_id" => "GALL-001",
                   "repository" => "seanchatmangpt/ggen",
                   "receipt_digest" => semantic_digest("a"),
                   "subject_digest" => semantic_digest("b"),
                   "subject_sha" => String.duplicate("c", 40),
                   "standing" => "ALIVE"
                 }
               ])

      assert composition["standing"] == "UNKNOWN"
      assert composition["inherited_standing"] == false

      replay = %{
        "pack_subject" => "semantic-jira-pack@26.9.19",
        "dependency_set" => [semantic_digest("a")],
        "graph_digest" => semantic_digest("b"),
        "consequence_set" => [semantic_digest("c")],
        "toolchain_identity" => "elixir:1.18.4-otp-27",
        "environment_identity" => "darwin:local",
        "replay_identity" => "replay:1"
      }

      assert {:ok, %{"status" => "KNOWN_REPLAY"}} =
               SemanticJira.replay_check(
                 replay,
                 Map.put(replay, "candidate_subjects", ["pack:1"])
               )

      assert {:error, {:replay_refused, {:ambiguous_subject_selection, 2}}} =
               SemanticJira.replay_check(
                 replay,
                 Map.put(replay, "candidate_subjects", ["pack:1", "pack:2"])
               )
    end

    test "semantic diff, repair, process findings, views, and all projections are deterministic" do
      before = sample_work_order(%{"notes" => "old prose"})
      after_prose = %{before | "notes" => "new prose"}
      assert SemanticJira.semantic_diff(before, after_prose)["semantic_equal"] == true

      after_semantic = %{before | "evidence_ceiling" => "hosted-ci"}
      assert SemanticJira.semantic_diff(before, after_semantic)["semantic_change_count"] == 1

      assert {:ok, repair} =
               SemanticJira.repair_work_order(before, %{
                 "failed_receipt_digest" => semantic_digest("a"),
                 "hypothesis" => "graph identity was stale",
                 "smallest_repair" => "bind the fresh graph digest",
                 "permanent_guard" => "reject stale graph receipts",
                 "changed_identities" => ["graph_digest"],
                 "verifier" => "court:graph-replay"
               })

      assert repair["blind_rerun_allowed"] == false

      assert {:ok, finding} =
               SemanticJira.process_finding(%{
                 "normative_model_digest" => semantic_digest("b"),
                 "observed_model_digest" => semantic_digest("c"),
                 "delta" => %{"unexpected" => ["activity:x"]},
                 "observation_receipt_digest" => semantic_digest("d")
               })

      assert finding["normative_model_mutated"] == false
      assert finding["authority"] == "NONE"
      assert SemanticJira.view(before, :executive)["authority"] == "NONE"

      context = %{"graph_digest" => semantic_digest("f")}

      rendered =
        Map.new(SemanticJira.projection_types(), fn type ->
          {type, SemanticJira.render_projection(type, before, context)}
        end)

      assert map_size(rendered) == 14
      assert Enum.all?(rendered, fn {_type, bytes} -> bytes =~ "authority=NONE" end)

      assert rendered ==
               Map.new(SemanticJira.projection_types(), fn type ->
                 {type, SemanticJira.render_projection(type, before, context)}
               end)
    end
  end
end
