defmodule GgenIgniter.SemanticJiraPackTest do
  @moduledoc """
  Chicago-style, no-mocks integration proof for semantic-jira-pack.

  Uses the real Core-profile pack manifest admission, RDF/Turtle loader, SPARQL
  engine, for-each Reactor render/admission/actuation path, real filesystem,
  real nested mix compile verification, and durable GgenIgniter receipts.
  """

  use ExUnit.Case, async: false

  @moduletag :integration

  alias GgenIgniter.{Receipt, SemanticJira}

  @ontology_path "priv/ggen/semantic-jira-pack/ontology.ttl"

  defp scratch_dir!(tag) do
    dir =
      Path.join(
        System.tmp_dir!(),
        "ggen_igniter_semantic_jira_#{tag}_#{System.unique_integer([:positive])}"
      )

    File.rm_rf!(dir)
    File.mkdir_p!(dir)

    # The receipt layer stores realpath'd (/private/var/...) file keys while
    # System.tmp_dir!() hands out /var/... on macOS; return the real path so
    # path expectations match the SUT's canonical storage (bccf084 pattern).
    dir = RealDir.real_dir!(dir)

    on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  defp run_sync(work_dir, extra_args \\ []) do
    out_template = Path.join(work_dir, "<%= id %>.md")

    args = [
      "ggen_igniter.sync",
      "--engine",
      "sparql",
      "--pack",
      "semantic-jira-pack:jira",
      "--out",
      out_template,
      "--manifest-dir",
      work_dir,
      "--verify-cwd",
      File.cwd!()
    ]

    System.cmd("mix", args ++ extra_args,
      cd: File.cwd!(),
      stderr_to_stdout: true
    )
  end

  defp sha256_file(path) do
    "sha256:" <>
      (:crypto.hash(:sha256, File.read!(path))
       |> Base.encode16(case: :lower))
  end

  describe "canonical WorkOrder graph -> deterministic Markdown projection -> graph-bound receipt" do
    test "manufactures all canonical WorkOrders and replays byte-identically" do
      work_dir = scratch_dir!("projection")
      output_path = Path.join(work_dir, "SJ-001.md")

      {first_output, first_exit} = run_sync(work_dir)

      assert first_exit == 0, "first Semantic Jira sync failed:\n#{first_output}"
      assert File.exists?(output_path)
      assert File.exists?(Path.join(work_dir, "GALL-001.md"))
      assert File.exists?(Path.join(work_dir, "GALL-032.md"))
      assert length(Path.wildcard(Path.join(work_dir, "*.md"))) == 33

      first_bytes = File.read!(output_path)

      assert first_bytes =~
               "<!-- GENERATED by semantic-jira-pack from canonical RDF WorkOrder"

      assert first_bytes =~ "# SJ-001 — Manufacture Semantic Jira work orders from RDF"
      assert first_bytes =~ "**Base SHA:** d84da1419a6945c6a8a64b8f6cdca9d0b2c9e0f3"
      assert first_bytes =~ "**Standing:** UNKNOWN"
      assert first_bytes =~ "**Authority ceiling:** CONSTRUCT"
      assert first_bytes =~ "zero independent actuation"
      assert first_bytes =~ "Missing required field still renders"
      assert first_bytes =~ "Add a qualified SHACL court"

      [first_receipt] = Receipt.read_all!(work_dir)
      assert first_receipt["standing"] == "alive"
      assert output_path in first_receipt["files"]
      assert first_receipt["metadata"]["graph_hash"] == sha256_file(@ontology_path)

      {second_output, second_exit} = run_sync(work_dir)

      assert second_exit == 0, "second Semantic Jira sync failed:\n#{second_output}"
      assert File.read!(output_path) == first_bytes

      receipts = Receipt.read_all!(work_dir)
      assert length(receipts) == 2

      [first_graph_hash, second_graph_hash] =
        Enum.map(receipts, &get_in(&1, ["metadata", "graph_hash"]))

      assert first_graph_hash == second_graph_hash
      assert second_graph_hash == sha256_file(@ontology_path)
    end
  end

  describe "semantic admission falsifier" do
    test "removing a required baseSha refuses before any ticket is actuated" do
      work_dir = scratch_dir!("missing_base_sha")
      broken_ontology = Path.join(work_dir, "missing-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/^    sj:baseSha "[0-9a-f]+" ;\n/m,
          "",
          global: false
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, [
          "--ontology",
          broken_ontology
        ])

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing core field base_sha"
      refute File.exists?(Path.join(work_dir, "SJ-001.md"))

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end

  describe "graph-binding tripwires" do
    test "every pack gate executes cleanly against the canonical graph" do
      graph = GgenIgniter.Ontology.load!(@ontology_path)

      gates =
        "priv/ggen/semantic-jira-pack/gates/*.rq"
        |> Path.wildcard()
        |> Enum.sort()

      assert length(gates) == 5

      Enum.each(gates, fn gate ->
        assert is_list(GgenIgniter.Query.run(graph, File.read!(gate))),
               "gate #{Path.basename(gate)} does not execute against the canonical graph"
      end)

      # The self-dogfood WorkOrder has no dependency edges, so the frontier
      # gate (nested MINUS, not FILTER NOT EXISTS — see 050_frontier.rq) must
      # keep it eligible; an inverted or crashing frontier loses it.
      frontier_rows =
        graph
        |> GgenIgniter.Query.run(File.read!("priv/ggen/semantic-jira-pack/gates/050_frontier.rq"))

      frontier_ids = Enum.map(frontier_rows, & &1["id"])

      assert "SJ-001" in frontier_ids
      refute frontier_ids == []
    end

    test "mutating a scalar fact in the graph changes the projection" do
      work_dir = scratch_dir!("scalar_mutation")
      mutated_ontology = Path.join(work_dir, "mutated-title.ttl")

      old_title = "Manufacture Semantic Jira work orders from RDF"
      new_title = "Manufacture Semantic Jira work orders from canonical RDF"

      source = File.read!(@ontology_path)
      mutated = String.replace(source, old_title, new_title)

      refute mutated == source
      File.write!(mutated_ontology, mutated)

      {output, exit_code} = run_sync(work_dir, ["--ontology", mutated_ontology])

      assert exit_code == 0, "mutated-graph sync failed:\n#{output}"

      projected = File.read!(Path.join(work_dir, "SJ-001.md"))
      assert projected =~ new_title
      refute projected =~ old_title
    end

    test "deleting a required relation refuses before any ticket is actuated" do
      work_dir = scratch_dir!("missing_relation")
      broken_ontology = Path.join(work_dir, "missing-requires-court.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          "sj:requiresCourt sj:exact-head-projection-court",
          "sj:requiresCourtX sj:exact-head-projection-court"
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, [
          "--ontology",
          broken_ontology
        ])

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "missing required requiresCourt relation for SJ-001"
      assert Path.wildcard(Path.join(work_dir, "*.md")) == []

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end

    test "corrupting baseSha to a non-SHA scalar refuses before any ticket is actuated" do
      work_dir = scratch_dir!("corrupt_base_sha")
      broken_ontology = Path.join(work_dir, "corrupt-base-sha.ttl")

      source = File.read!(@ontology_path)

      broken =
        String.replace(
          source,
          ~r/sj:baseSha "[0-9a-f]{40}"/,
          ~s{sj:baseSha "main"},
          global: true
        )

      refute broken == source
      File.write!(broken_ontology, broken)

      {output, exit_code} =
        run_sync(work_dir, [
          "--ontology",
          broken_ontology
        ])

      refute exit_code == 0
      assert output =~ "REFUSED:SEMANTIC_JIRA_INVALID_WORK_ORDER"
      assert output =~ "baseSha must be an exact 40-hex commit SHA"
      assert Path.wildcard(Path.join(work_dir, "*.md")) == []

      receipts = Receipt.read_all!(work_dir)

      assert Enum.all?(receipts, fn receipt ->
               receipt["standing"] != "alive"
             end)
    end
  end

  defp semantic_digest(seed), do: "sha256:" <> String.duplicate(seed, 64)

  defp sample_work_order(overrides \\ %{}) do
    Map.merge(
      %{
        "identity" => "SJ-TEST-001",
        "title" => "Bounded semantic test",
        "description" => "Exercise the kernel without granting authority.",
        "subject" => "urn:subject:test",
        "repository" => "seanchatmangpt/ggen_igniter",
        "base_sha" => String.duplicate("a", 40),
        "standing" => "UNKNOWN",
        "evidence_ceiling" => "repository-local",
        "promotion_rule" => "exact subject and independent evidence",
        "replay_identity" => "semantic-jira:test:1",
        "dependencies" => [],
        "required_courts" => ["court:test"],
        "required_evidence" => ["source", "verification"],
        "acceptance" => ["acceptance:test"],
        "falsifiers" => ["falsifier:test"],
        "projections" => SemanticJira.projection_types(),
        "required_receipt_classes" => ["verification"],
        "path_scope" => ["lib/ggen_igniter"],
        "authority_requirement" => "NONE",
        "replay_required" => false
      },
      overrides
    )
  end

  describe "DfCM semantic kernel" do
    test "admission, frontier, scheduling, lease requests, and worker packages preserve boundaries" do
      work_order = sample_work_order()
      reversed = work_order |> Enum.reverse() |> Map.new()

      {:ok, first} = SemanticJira.admit_work_order(work_order)
      {:ok, second} = SemanticJira.admit_work_order(reversed)
      assert first["work_order_digest"] == second["work_order_digest"]
      assert first["authority"] == "NONE"

      assert {:error, {:invalid_sha, :base_sha, "main"}} =
               SemanticJira.admit_work_order(%{work_order | "base_sha" => "main"})

      dependent =
        sample_work_order(%{
          "identity" => "DOWNSTREAM",
          "dependencies" => [
            %{
              "upstream" => "UPSTREAM",
              "type" => "requiresReceipt",
              "required_standing" => "ALIVE",
              "required_receipt_digest" => semantic_digest("b")
            }
          ]
        })

      evidence = %{
        "UPSTREAM" => %{
          "standing" => "ALIVE",
          "receipt_digest" => semantic_digest("b")
        }
      }

      assert [%{"identity" => "DOWNSTREAM", "authority" => "NONE"}] =
               SemanticJira.frontier([dependent], evidence).eligible

      scheduled =
        SemanticJira.schedule(
          [dependent],
          [
            %{
              "status" => "active",
              "repository" => "seanchatmangpt/ggen_igniter",
              "scope" => ["lib/ggen_igniter/semantic_jira.ex"]
            }
          ],
          evidence
        )

      assert scheduled.eligible == []
      assert Enum.any?(scheduled.blocked, &(&1["reason"] == "conflicting_active_lease"))

      lease_attrs = %{
        "run_id" => "run-1",
        "epoch_id" => "epoch-1",
        "worker_identity" => "zcode-cli:worker-7",
        "scope" => ["lib/ggen_igniter/semantic_jira.ex"],
        "allowed_operations" => ["read", "edit", "test"],
        "expiration" => "2026-09-20T00:00:00Z",
        "concurrency_key" => "ggen_igniter:semantic-jira"
      }

      assert {:ok, request} = SemanticJira.lease_request(work_order, lease_attrs)
      assert request["owner"] == "XaaS/Ultracode"
      assert request["authority"] == "NONE"

      assert {:ok, package} =
               SemanticJira.execution_package(work_order, %{
                 "graph_digest" => semantic_digest("c"),
                 "source_digest" => semantic_digest("d"),
                 "worker_identity" => "zcode-cli:worker-7",
                 "verifier_identity" => "court:independent-1"
               })

      assert package.subject_id == "urn:subject:test"
      assert hd(package.actions)["authority"] == "NONE"
    end

    test "DO intent fails closed on claim-store error and crash windows stay explicit" do
      work_order = sample_work_order(%{"authority_requirement" => "repo-write"})
      {:ok, admitted} = SemanticJira.admit_work_order(work_order)

      authority = %{
        "status" => "prepared",
        "work_order_digest" => admitted["work_order_digest"],
        "subject" => admitted["subject"],
        "replay_identity" => admitted["replay_identity"],
        "authority_identity" => "authority:1"
      }

      attrs = %{
        "claim_store_status" => "error",
        "prepared_authority_receipt" => authority,
        "lease_id" => "lease:1",
        "capability_identity" => "capability:test",
        "command_identity" => "command:test"
      }

      assert {:error, {:refused_do, :claim_store_unavailable}} =
               SemanticJira.do_intent(work_order, attrs)

      assert {:ok, intent} =
               SemanticJira.do_intent(
                 work_order,
                 %{attrs | "claim_store_status" => "available"}
               )

      assert intent["executed"] == false
      assert intent["owner"] == "BRCE/CommandBus"

      assert {:ok, %{"reconciliation_state" => "EFFECT_OBSERVED_RECEIPT_MISSING"}} =
               SemanticJira.reconcile_crash_window(%{
                 "effect_identity" => "effect:1",
                 "claim_state" => "committed",
                 "consequence_observed" => true,
                 "receipt_state" => "absent"
               })
    end

    test "verification, promotion, MachineExperience, composition, and replay require exact evidence" do
      {:ok, work_order} = SemanticJira.admit_work_order(sample_work_order())

      assert {:ok, verification} =
               SemanticJira.exact_head_verification_evidence(%{
                 "repository" => work_order["repository"],
                 "base_sha" => work_order["base_sha"],
                 "candidate_sha" => String.duplicate("b", 40),
                 "work_order_digest" => work_order["work_order_digest"],
                 "projection_digest" => semantic_digest("d"),
                 "command" => "mix test",
                 "exit_code" => 0,
                 "toolchain_identity" => "elixir:1.18.4-otp-27",
                 "environment_identity" => "ubuntu:hosted",
                 "validator_identity" => "court:test",
                 "test_result_digest" => semantic_digest("e"),
                 "falsifier_results" => [
                   %{"name" => "identity", "verdict" => "survived"}
                 ]
               })

      assert verification["passed"] == true
      assert verification["standing_authority"] == "NONE"

      evidence = %{
        "work_order_digest" => work_order["work_order_digest"],
        "subject" => work_order["subject"],
        "repository" => work_order["repository"],
        "base_sha" => work_order["base_sha"],
        "dependency_evidence" => %{},
        "court_results" => %{"court:test" => %{"passed" => true}},
        "evidence_types" => ["source", "verification"],
        "acceptance_results" => %{"acceptance:test" => true},
        "falsifier_results" => %{"falsifier:test" => "survived"},
        "receipt_classes" => ["verification"],
        "evidence_ceiling" => work_order["evidence_ceiling"],
        "observed_execution" => true,
        "inherited_standing" => false
      }

      assert {:ok, transition} =
               SemanticJira.promote(work_order, "ALIVE", evidence)

      assert transition["authority"] == "NONE"

      assert {:error, {:promotion_refused, failed}} =
               SemanticJira.promote(
                 work_order,
                 "ALIVE",
                 %{evidence | "inherited_standing" => true}
               )

      assert :no_inherited_crown in failed

      experience_attrs = %{
        "subject" => work_order["subject"],
        "work_order_digest" => work_order["work_order_digest"],
        "execution_receipt" => %{
          "executed" => true,
          "receipt_hash" => semantic_digest("a")
        },
        "observation_refs" => ["ocel:event:1"],
        "verification" => %{"passed" => true},
        "resulting_state" => %{"digest" => semantic_digest("b")},
        "replay_identity" => work_order["replay_identity"]
      }

      assert {:ok, experience} =
               SemanticJira.machine_experience(experience_attrs)

      assert experience["standing"] == "CANDIDATE"

      assert {:error, {:refused_machine_experience, :prediction_only}} =
               SemanticJira.machine_experience(Map.put(experience_attrs, "prediction_only", true))

      assert {:ok, composition} =
               SemanticJira.composition_subject([
                 %{
                   "work_order_id" => "GALL-001",
                   "repository" => "seanchatmangpt/ggen",
                   "receipt_digest" => semantic_digest("a"),
                   "subject_digest" => semantic_digest("b"),
                   "subject_sha" => String.duplicate("c", 40),
                   "standing" => "ALIVE"
                 }
               ])

      assert composition["standing"] == "UNKNOWN"
      assert composition["inherited_standing"] == false

      replay = %{
        "pack_subject" => "semantic-jira-pack@26.9.19",
        "dependency_set" => [semantic_digest("a")],
        "graph_digest" => semantic_digest("b"),
        "consequence_set" => [semantic_digest("c")],
        "toolchain_identity" => "elixir:1.18.4-otp-27",
        "environment_identity" => "darwin:local",
        "replay_identity" => "replay:1"
      }

      assert {:ok, %{"status" => "KNOWN_REPLAY"}} =
               SemanticJira.replay_check(
                 replay,
                 Map.put(replay, "candidate_subjects", ["pack:1"])
               )

      assert {:error, {:replay_refused, {:ambiguous_subject_selection, 2}}} =
               SemanticJira.replay_check(
                 replay,
                 Map.put(replay, "candidate_subjects", ["pack:1", "pack:2"])
               )
    end

    test "semantic diff, repair, process findings, views, and all projections are deterministic" do
      before = sample_work_order(%{"notes" => "old prose"})
      after_prose = %{before | "notes" => "new prose"}
      assert SemanticJira.semantic_diff(before, after_prose)["semantic_equal"] == true

      after_semantic = %{before | "evidence_ceiling" => "hosted-ci"}
      assert SemanticJira.semantic_diff(before, after_semantic)["semantic_change_count"] == 1

      assert {:ok, repair} =
               SemanticJira.repair_work_order(before, %{
                 "failed_receipt_digest" => semantic_digest("a"),
                 "hypothesis" => "graph identity was stale",
                 "smallest_repair" => "bind the fresh graph digest",
                 "permanent_guard" => "reject stale graph receipts",
                 "changed_identities" => ["graph_digest"],
                 "verifier" => "court:graph-replay"
               })

      assert repair["blind_rerun_allowed"] == false

      assert {:ok, finding} =
               SemanticJira.process_finding(%{
                 "normative_model_digest" => semantic_digest("b"),
                 "observed_model_digest" => semantic_digest("c"),
                 "delta" => %{"unexpected" => ["activity:x"]},
                 "observation_receipt_digest" => semantic_digest("d")
               })

      assert finding["normative_model_mutated"] == false
      assert finding["authority"] == "NONE"
      assert SemanticJira.view(before, :executive)["authority"] == "NONE"

      context = %{"graph_digest" => semantic_digest("f")}

      rendered =
        Map.new(SemanticJira.projection_types(), fn type ->
          {type, SemanticJira.render_projection(type, before, context)}
        end)

      assert map_size(rendered) == 14
      assert Enum.all?(rendered, fn {_type, bytes} -> bytes =~ "authority=NONE" end)

      assert rendered ==
               Map.new(SemanticJira.projection_types(), fn type ->
                 {type, SemanticJira.render_projection(type, before, context)}
               end)
    end
  end
end
