defmodule GgenIgniter.PackCompileTest do
  @moduledoc """
  Chicago-style: `GgenIgniter.Test.PackCompile` is exercised end to end with real
  collaborators only: a real `mix ggen_igniter.sync` subprocess renders
  `priv/ggen/receipted-extension-pack` from the real fixture ontology into a real
  tmp dir, and the real Elixir compiler builds the output. Assertions are on
  returned state (file lists, modules, diagnostics, code-server state). Falsifier:
  a corrupted rendered file must make `compile/2` return `{:error, diagnostics}`.
  No doubles.
  """
  use ExUnit.Case, async: false
  # async: false -- compiles same-named modules into the global code server.

  alias GgenIgniter.Test.PackCompile
  alias GgenIgniter.Test.PackCompile.{RenderError, CompileError}

  @moduletag :integration
  @moduletag timeout: 1_200_000

  @pack "receipted-extension-pack"
  @pack_dir Path.expand("../priv/ggen/#{@pack}", __DIR__)
  @fixture Path.expand("fixtures/receipted-extension/consumer.ttl", __DIR__)
  @ext ReceiptedFixture.Receipted

  setup_all do
    dir = PackCompile.tmp_project!(%{})
    on_exit(fn -> PackCompile.cleanup(dir) end)
    ontology = Path.join(dir, "consumer.ttl")

    File.write!(
      ontology,
      File.read!(Path.join(@pack_dir, "ontology.ttl")) <> "\n" <> File.read!(@fixture)
    )

    %{ontology: ontology}
  end

  setup do
    on_exit(fn ->
      for m <- [@ext, ReceiptedFixture.Receipted.Verifier, ReceiptedFixture.ReceiptedVerifier] do
        :code.purge(m)
        :code.delete(m)
      end
    end)

    :ok
  end

  describe "render!/2 + compile/2 (real subprocess, real compiler)" do
    test "renders a pack and the output compiles to a callable module", %{ontology: ontology} do
      r = PackCompile.render!("#{@pack}:extension", ontology: ontology, out: "lib/receipted.ex")
      on_exit(fn -> PackCompile.cleanup(r.out_dir) end)

      assert File.dir?(r.out_dir)
      assert r.output =~ "receipted"
      assert Enum.map(r.files, &Path.relative_to(&1, r.out_dir)) == ["lib/receipted.ex"]
      assert File.read!(hd(r.files)) =~ "GENERATED by receipted-extension-pack"

      modules = PackCompile.compile!(r.files)
      assert @ext in modules
      assert function_exported?(@ext, :receipts, 1)
      PackCompile.purge(modules)
    end

    test "FALSIFIER: a corrupted rendered file yields {:error, diagnostics} with file and line",
         %{ontology: ontology} do
      r = PackCompile.render!("#{@pack}:extension", ontology: ontology, out: "lib/receipted.ex")
      on_exit(fn -> PackCompile.cleanup(r.out_dir) end)
      [file] = r.files
      File.write!(file, File.read!(file) <> "\ndefmodule Broken do\n  def x( do\nend\n")

      assert {:error, diagnostics} = PackCompile.compile([file])
      assert [_ | _] = diagnostics

      injected_line =
        File.read!(file)
        |> String.split("\n")
        |> Enum.find_index(&(&1 == "defmodule Broken do"))
        |> Kernel.+(1)

      # the diagnostic must point at the injected `def x(` error in THIS file
      assert Enum.any?(diagnostics, fn d ->
               d.severity == :error and d.file == file and is_integer(d.line) and
                 d.line >= injected_line and
                 (d.message =~ "missing terminator" or d.message =~ "unexpected" or
                    d.message =~ "syntax error")
             end),
             "no diagnostic tied to the injected error (line >= #{injected_line}): " <>
               inspect(diagnostics)

      assert_raise CompileError, fn -> PackCompile.compile!([file]) end
    end

    test "render/2 returns a typed refusal attributable to the bad gate, render!/2 raises it" do
      # The repo's fixtures/broken-pack has no templates/ dir, so it fails for an
      # unrelated reason and cannot attribute a refusal. Build a structurally
      # complete pack whose ONLY defect is an unparseable gate query.
      bad = tmp_pack!("this is not sparql\n")
      good = tmp_pack!("SELECT ?s WHERE { ?s ?p ?o }\n")

      # control: the identical pack with a valid gate is admitted (defect is the gate)
      assert {:ok, %{files: [_ | _]} = ok} = PackCompile.render("ctl", pack_dir: good)
      on_exit(fn -> PackCompile.cleanup(ok.out_dir) end)

      assert {:error, %{exit_status: 1, output: out}} = PackCompile.render("bad", pack_dir: bad)
      refute out =~ "timed out"
      assert out =~ "SPARQL language scanner error"
      assert out =~ "refused"

      assert_raise RenderError, ~r/SPARQL language scanner error/, fn ->
        PackCompile.render!("bad", pack_dir: bad)
      end
    end

    test "a missing pack fails for a different reason than a bad gate" do
      missing = Path.join(System.tmp_dir!(), "no_such_pack_#{System.unique_integer([:positive])}")
      assert {:error, %{exit_status: 1, output: out}} = PackCompile.render("x", pack_dir: missing)
      refute out =~ "SPARQL language scanner error"
    end

    test "timeout kills the real OS process tree, not just the Erlang task" do
      marker = "pcmarker_" <> Base.encode16(:crypto.strong_rand_bytes(8), case: :lower)
      dir = Path.join(System.tmp_dir!(), marker)
      File.mkdir_p!(dir)
      on_exit(fn -> PackCompile.cleanup(dir) end)

      assert {:error, %{exit_status: 124, output: out}} =
               PackCompile.render("slow", pack_dir: dir, timeout: 50)

      assert out =~ "timed out after 50ms"
      Process.sleep(500)
      {ps, _} = System.cmd("ps", ["-axo", "command"])
      refute ps =~ marker, "mix subprocess for #{marker} survived the timeout"
    end
  end

  describe "with_compiled/3" do
    test "passes modules and render result, then purges", %{ontology: ontology} do
      result =
        PackCompile.with_compiled("#{@pack}:extension", [ontology: ontology], fn mods, r ->
          assert @ext in mods
          assert :code.is_loaded(@ext) != false
          {mods, r.out_dir}
        end)

      {mods, out_dir} = result
      assert @ext in mods
      assert :code.is_loaded(@ext) == false
      refute File.exists?(out_dir)
    end

    test "purges even when the callback raises", %{ontology: ontology} do
      assert_raise RuntimeError, "boom", fn ->
        PackCompile.with_compiled("#{@pack}:extension", [ontology: ontology], fn _m, _r ->
          raise "boom"
        end)
      end

      assert :code.is_loaded(@ext) == false
    end
  end

  describe "load_path and purge/1 (code-path removal)" do
    test "extra load_path is removed after compile; purge drops the tmp ebin from the path" do
      extra = PackCompile.tmp_project!(%{})
      on_exit(fn -> PackCompile.cleanup(extra) end)
      extra_c = String.to_charlist(extra)

      dir =
        PackCompile.tmp_project!(%{
          "m.ex" => "defmodule PcLoadPathProbe do\n  def ok, do: :ok\nend\n"
        })

      on_exit(fn -> PackCompile.cleanup(dir) end)

      modules = PackCompile.compile!(dir, load_path: [extra])
      assert PcLoadPathProbe in modules
      refute extra_c in :code.get_path()

      ebin = :code.which(PcLoadPathProbe) |> List.to_string() |> Path.dirname()
      assert String.to_charlist(ebin) in :code.get_path()

      assert :ok = PackCompile.purge(modules)
      assert :code.is_loaded(PcLoadPathProbe) == false
      refute String.to_charlist(ebin) in :code.get_path()
      refute File.exists?(ebin)
    end
  end

  describe "tmp_project!/1 and cleanup/1" do
    test "creates real files and removes them" do
      dir = PackCompile.tmp_project!(%{"a/b.ex" => "defmodule PcTmp do\nend\n", "c.txt" => "x"})
      assert File.read!(Path.join(dir, "c.txt")) == "x"
      assert [_] = Path.wildcard(Path.join(dir, "**/*.ex"))
      assert :ok = PackCompile.cleanup(dir)
      refute File.exists?(dir)
    end
  end

  # A complete pack (pack.toml, ontology, one gate, one template) whose gate query is `gate`.
  defp tmp_pack!(gate) do
    dir =
      PackCompile.tmp_project!(%{
        "pack.toml" => "[pack]\nname = \"tmp-pack\"\nversion = \"0.0.1\"\n",
        "ontology.ttl" => "@prefix ex: <http://e/> .\nex:a ex:b ex:c .\n",
        "gates/010_gate.rq" => gate,
        "templates/out.eex" => "hello\n"
      })

    on_exit(fn -> PackCompile.cleanup(dir) end)
    dir
  end
end
