defmodule GgenIgniter.SemanticJiraProseTest do
  @moduledoc """
  Chicago-style: proof of the observation surface (GC-26.9.23 GC23-0 / GC23-2;
  PRD PR-002..PR-005, ARD sections 5 and 17), `GgenIgniter.SemanticJira.Prose.observe/1`
  and `mix semantic_jira.observe_prose`.

  Real collaborators only: the committed fixture prose, candidates and goal
  under `test/fixtures/semantic-jira-prose/` (the candidates were emitted by
  the real xaas `scripts/sjira/prose_spans.py emit` from `extract.json`),
  copied into unique tmp trees and mutated as real files; the real pack
  ontology and its `shapes/*.shacl.ttl` courts; and real
  `mix semantic_jira.observe_prose` subprocesses (with every LLM credential
  variable unset). No mocks, stubs or test doubles.

  The observer is authority-neutral by construction. It manufactures zero
  work orders: the observed projection is one `propositions.ttl` in which
  every admitted proposition is stamped `sj:candidateStanding "UNKNOWN"` and
  `sj:authorityClaim "NONE"` and carries no admission digest at all.
  `admit_goal/1` is the only digest-stamping path: it runs the GC23-3 shapes
  court over the goal graph and then stamps every authority-bearing subject
  through `GgenIgniter.SemanticJira.Authority.admit/2`, overwriting any
  pre-existing (placeholder) digest rather than trusting it.
  """

  # async: false -- the CLI subprocesses share this checkout's _build.
  use ExUnit.Case, async: false

  @moduletag :integration

  alias GgenIgniter.SemanticJira.{Authority, Prose}

  @fixture_dir "test/fixtures/semantic-jira-prose"
  @sj "https://ggen-igniter.dev/ontology/semantic-jira#"
  @ns "https://ggen-igniter.dev/sjira/fixture-prose#"
  @source_sha "sha256:a08df167fb31a4493373cd19c70249acc722cdc5e8253c2632a3aa461380f5d6"

  # Fixture propositions (IRIs recompute per PVOCAB from the committed spans).
  @actor @ns <> "P-93e73ffcc7345c79"
  @format_post @ns <> "P-a9d665f1e22ef256"
  @invariant @ns <> "P-cd9ee31a70d470ae"
  @exclusion @ns <> "P-e3a10ad82ca48d34"
  @replay_post @ns <> "P-e169d0fdca152ff4"
  @falsifier @ns <> "P-83afd960b0459690"
  @metric @ns <> "P-d5f6ba90710b016d"
  @root_post @ns <> "P-05d08155a5fcc6c8"
  @successor @ns <> "P-f22085da12196d3b"

  @all [
    @actor,
    @format_post,
    @invariant,
    @exclusion,
    @replay_post,
    @falsifier,
    @metric,
    @root_post,
    @successor
  ]

  @llm_env ~w(ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL CLAUDE_CODE_OAUTH_TOKEN OPENAI_API_KEY
              ZAI_API_KEY Z_AI_API_KEY GLM_API_KEY ZCODE_API_KEY)

  setup do
    tmp = Path.join(System.tmp_dir!(), "gi-prose-#{System.unique_integer([:positive])}")
    File.rm_rf!(tmp)
    File.mkdir_p!(tmp)
    on_exit(fn -> File.rm_rf!(tmp) end)
    %{tmp: tmp}
  end

  describe "observe/1 (observation over the committed fixture)" do
    test "admits every candidate and stamps UNKNOWN standing with NO authority onto each" do
      assert {:ok, result} = Prose.observe(fixture_opts())

      assert result.summary.admitted == 9
      assert result.summary.required == 7
      assert result.summary.not_required == 2

      assert result.summary.required_by == %{
               "GC-PROSE" => 1,
               "GCP-0" => 3,
               "GCP-1" => 2,
               "GCP-2" => 1
             }

      assert result.propositions_ttl =~ ~r/\A# GENERATED by mix semantic_jira\.observe_prose\b/

      admitted = RDF.Turtle.read_string!(result.propositions_ttl)
      assert length(instances(admitted, "Proposition")) == 9
      assert Enum.all?(objects(admitted, "candidateStanding"), &(&1 == "UNKNOWN"))
      assert Enum.all?(objects(admitted, "authorityClaim"), &(&1 == "NONE"))
      assert objects(admitted, "admissionDigest") == []
    end

    test "a second run is byte-identical and check/2 confirms the written propositions", %{
      tmp: tmp
    } do
      assert {:ok, first} = Prose.observe(fixture_opts())
      assert {:ok, second} = Prose.observe(fixture_opts())

      assert first.propositions_ttl == second.propositions_ttl

      out = Path.join(tmp, "out")
      Prose.write!(first, out)
      assert :ok = Prose.check(second, out)

      File.write!(Path.join(out, "propositions.ttl"), first.propositions_ttl <> "\n")
      assert {:refused, [refusal]} = Prose.check(second, out)
      assert refusal.code == :output_drift
      assert refusal.subject == Path.join(out, "propositions.ttl")
    end
  end

  describe "observe/1 provenance admission (step a)" do
    test "one changed source byte refuses every proposition and the root, each by IRI", %{
      tmp: tmp
    } do
      opts =
        fixture_copy(tmp,
          source: [{"exits 0 on the exact subject", "exits 1 on the exact subject"}]
        )

      assert {:refused, refusals} = Prose.observe(opts)

      for proposition <- @all do
        assert Enum.any?(
                 refusals,
                 &(&1.code == :provenance_mismatch and &1.subject == proposition and
                     &1.detail =~ "sj:sourceSha256")
               ),
               "#{proposition} was not refused for the source digest"
      end

      assert Enum.any?(
               refusals,
               &(&1.subject == @ns <> "GC-PROSE" and &1.code == :provenance_mismatch)
             )
    end

    test "a changed sj:sourceText refuses exactly that proposition", %{tmp: tmp} do
      opts =
        fixture_copy(tmp,
          candidates: [
            {~s(sj:sourceText "No LLM runs on the KNOWN path."),
             ~s(sj:sourceText "No LLM runs on any path.")}
          ]
        )

      assert {:refused, refusals} = Prose.observe(opts)
      assert [%{code: :provenance_mismatch, subject: @invariant} = refusal] = provenance(refusals)
      assert refusal.detail =~ "!= sj:sourceText"
    end

    test "a shifted offset refuses the proposition (span bytes and IRI no longer recompute)", %{
      tmp: tmp
    } do
      opts = fixture_copy(tmp, candidates: [{"sj:sourceStart 258 ;", "sj:sourceStart 259 ;"}])

      assert {:refused, refusals} = Prose.observe(opts)
      mismatches = provenance(refusals)
      assert Enum.all?(mismatches, &(&1.subject == @invariant))
      assert Enum.any?(mismatches, &(&1.detail =~ "!= sj:sourceText"))
      assert Enum.any?(mismatches, &(&1.detail =~ "IRI does not recompute"))
    end

    test "a renamed candidate IRI refuses (the IRI must recompute per PVOCAB)", %{tmp: tmp} do
      opts =
        fixture_copy(tmp, candidates: [{"fx:P-cd9ee31a70d470ae a", "fx:P-0000000000000000 a"}])

      assert {:refused, refusals} = Prose.observe(opts)
      assert [refusal] = provenance(refusals)
      assert refusal.subject == @ns <> "P-0000000000000000"
      assert refusal.detail == "IRI does not recompute per PVOCAB: expected #{@invariant}"
    end

    test "an anonymous (blank-node) candidate has no identity and is refused", %{tmp: tmp} do
      anonymous =
        exclusion_candidate("Replays never reach an LLM provider.")
        |> String.replace(~r/<[^>]+> a sj:Proposition/, "[] a sj:Proposition", global: false)

      assert anonymous =~ "[] a sj:Proposition"

      assert {:refused, refusals} =
               Prose.observe(fixture_copy(tmp, candidates: [{:append, anonymous}]))

      assert Enum.any?(refusals, fn refusal ->
               refusal.code == :provenance_mismatch and String.starts_with?(refusal.subject, "_:") and
                 refusal.detail =~ "IRI does not recompute"
             end)
    end

    test "a candidate file cannot smuggle a non-proposition subject past admission", %{tmp: tmp} do
      smuggled = """

      fx:WO-SMUGGLED a sj:WorkOrder ;
          sj:subject "work nobody admitted" .
      """

      opts = fixture_copy(tmp, candidates: [{:append, smuggled}])

      assert {:refused, refusals} = Prose.observe(opts)

      assert Enum.any?(
               refusals,
               &(&1.code == :foreign_subject and &1.subject == @ns <> "WO-SMUGGLED")
             )
    end
  end

  describe "observe/1 SHACL and domain admission (steps b, c)" do
    test "a kind outside the ARD 5.2 list is refused by the proposition shape", %{tmp: tmp} do
      {start, stop} = {465, 506}
      wish = Prose.proposition_iri(@ns, @source_sha, start, stop, "Wish")

      opts =
        fixture_copy(tmp,
          candidates: [
            {"fx:P-d5f6ba90710b016d a", "<#{wish}> a"},
            {~s(sj:propositionKind "Metric"), ~s(sj:propositionKind "Wish")}
          ]
        )

      assert {:refused, refusals} = Prose.observe(opts)
      assert provenance(refusals) == []

      assert Enum.any?(refusals, fn refusal ->
               refusal.code == :shacl_violation and refusal.subject == wish and
                 refusal.detail =~ "#{@sj}propositionKind pattern"
             end)
    end

    test "an uncovered gate is refused by name", %{tmp: tmp} do
      gate = """

      fx:GCP-3 a sj:GoalCheckpoint ;
          dcterms:identifier "GCP-3" ;
          rdfs:label "GCP-3 unprosed gate" ;
          dcterms:description "A gate no admitted proposition requires." ;
          sj:checkpointOf fx:GC-PROSE ;
          sj:boundaryClass sj:Core ;
          sj:courtCommand "sh courts/GCP-3.sh" .
      """

      opts = fixture_copy(tmp, goal: [{:append, gate}])

      assert {:refused, [refusal]} = Prose.observe(opts)
      assert refusal.code == :uncovered_gate
      assert refusal.subject == @ns <> "GCP-3"
    end

    test "an Exclusion that restates a required Postcondition of the same gate is a contradiction",
         %{tmp: tmp} do
      contradicting =
        exclusion_candidate("Two replays of the compiler produce byte-identical outputs.")

      statement_ok = exclusion_candidate("Replays never reach an LLM provider.")

      assert {:refused, [refusal]} =
               Prose.observe(
                 fixture_copy(Path.join(tmp, "a"), candidates: [{:append, contradicting}])
               )

      assert refusal.code == :contradiction
      assert refusal.subject == Prose.proposition_iri(@ns, @source_sha, 342, 401, "Exclusion")
      assert refusal.detail =~ @replay_post

      # Anti-vacuity: the same added Exclusion with a different statement admits.
      assert {:ok, result} =
               Prose.observe(
                 fixture_copy(Path.join(tmp, "b"), candidates: [{:append, statement_ok}])
               )

      assert result.summary.admitted == 10
    end

    test "a proposition required by a checkpoint outside the root's gates is refused", %{tmp: tmp} do
      opts =
        fixture_copy(tmp,
          candidates: [{"sj:requiredBy fx:GCP-2 ;", "sj:requiredBy fx:GC-PROSE-NEXT ;"}]
        )

      assert {:refused, refusals} = Prose.observe(opts)
      assert Enum.any?(refusals, &(&1.code == :foreign_requirement and &1.subject == @metric))
      assert Enum.any?(refusals, &(&1.code == :uncovered_gate and &1.subject == @ns <> "GCP-2"))
    end
  end

  describe "admit_goal/1 (GC23-3 shapes court, then Authority stamping)" do
    @friday_goal "test/fixtures/semantic-jira-goal-checkpoint/goal.ttl"

    test "the fixture goal admits and every GoalCheckpoint carries exactly one recomputable digest" do
      assert {:ok, summary} = Prose.admit_goal(goal: @friday_goal)
      assert summary.work_orders == 1
      assert summary.goal_checkpoints == 3
      assert summary.goal_sha256 =~ ~r/\Asha256:[0-9a-f]{64}\z/

      graph = RDF.Turtle.read_string!(summary.stamped_ttl)
      checkpoints = instances(graph, "GoalCheckpoint")
      assert length(checkpoints) == 3

      for iri <- checkpoints do
        description = RDF.Graph.get(graph, RDF.iri(iri))
        assert [digest] = values(description, "admissionDigest")
        assert digest =~ ~r/\Asha256:[0-9a-f]{64}\z/

        assert digest == Authority.admission_digest(graph, iri),
               "#{iri}'s stamped digest does not recompute"

        assert summary.stamped[iri] == digest
      end
    end

    test "F1: deleting one mandatory tuple field of the goal's order is refused, naming it", %{
      tmp: tmp
    } do
      goal = Path.join(tmp, "goal.ttl")

      File.write!(
        goal,
        mutate!(
          {~s(    sj:postcondition "mix format --check-formatted exits 0 on the exact subject SHA" ;\n),
           ""},
          File.read!(@friday_goal)
        )
      )

      assert {:refused, refusals} = Prose.admit_goal(goal: goal)

      assert Enum.any?(refusals, fn refusal ->
               refusal.code == :goal_inadmissible and
                 refusal.subject == @sj <> "gc-fixture-wo-1" and
                 refusal.detail =~ "#{@sj}postcondition sparql"
             end)
    end

    test "a pre-existing placeholder digest is refused, never trusted or silently restamped", %{
      tmp: tmp
    } do
      goal = Path.join(tmp, "goal.ttl")

      File.write!(
        goal,
        mutate!(
          {"fx:GC-PROSE a sj:GoalCheckpoint ;\n",
           "fx:GC-PROSE a sj:GoalCheckpoint ;\n    sj:admissionDigest \"sha256:PENDING-SJ-002\" ;\n"},
          File.read!(Path.join(@fixture_dir, "goal.ttl"))
        )
      )

      # A placeholder is a malformed self-declared witness: the shapes court
      # (sj:AdmissionDigestShape) refuses it before stamping. Stamping
      # replaces digests only on goals that already admit.
      assert {:refused, refusals} = Prose.admit_goal(goal: goal)

      assert Enum.any?(refusals, fn refusal ->
               refusal.code == :goal_inadmissible and
                 refusal.subject == @ns <> "GC-PROSE" and
                 refusal.detail =~ "admissionDigest"
             end)
    end

    test "a predecessor reference resolves only through --context; context violations are out of scope",
         %{
           tmp: tmp
         } do
      successor = Path.join(tmp, "successor.ttl")

      File.write!(successor, """
      @prefix sj: <https://ggen-igniter.dev/ontology/semantic-jira#> .
      @prefix fx: <https://ggen-igniter.dev/sjira/fixture-prose#> .
      @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

      fx:GC-PROSE-SUCCESSOR a sj:GoalCheckpoint ;
          rdfs:label "Successor of GC-PROSE" ;
          sj:successorOf fx:GC-PROSE ;
          sj:stopQuery "ASK { FILTER(false) }" .
      """)

      assert {:refused, [refusal]} = Prose.admit_goal(goal: successor)
      assert refusal.subject == @ns <> "GC-PROSE-SUCCESSOR"
      assert refusal.detail =~ "#{@sj}successorOf class"

      context = Path.join(@fixture_dir, "goal.ttl")
      assert {:ok, summary} = Prose.admit_goal(goal: successor, context: [context])
      assert summary.goal_checkpoints == 1
    end
  end

  describe "mix semantic_jira.observe_prose (real subprocess, no LLM credentials)" do
    test "writes propositions only, --check confirms them, drift and refusals exit 1", %{tmp: tmp} do
      out = Path.join(tmp, "out")
      base = cli_args(fixture_opts()) ++ ["--out-dir", out]

      {output, status} = run_cli(base)
      assert status == 0, output
      assert output =~ "OBSERVED: 9 candidate propositions (7 required, 2 not required)"
      assert output =~ "KINDS: "

      # The digest value itself already carries the "sha256:" prefix; whether
      # the label adds a second one is the CLI's rendering, so the hex body is
      # what this pin commits to.
      assert output =~ ~r/propositions\.ttl sha256:(sha256:)?[0-9a-f]{64}/
      assert output =~ "WROTE: #{out}/propositions.ttl"
      assert File.ls!(out) == ["propositions.ttl"]

      assert {:ok, result} = Prose.observe(fixture_opts())
      assert File.read!(Path.join(out, "propositions.ttl")) == result.propositions_ttl

      {check_output, check_status} = run_cli(base ++ ["--check"])
      assert check_status == 0, check_output
      assert check_output =~ "CHECK: #{out}/propositions.ttl recomputes byte-identically"

      File.write!(Path.join(out, "propositions.ttl"), "# drift\n")
      {drift_output, drift_status} = run_cli(base ++ ["--check"])
      assert drift_status == 1
      assert drift_output =~ "REFUSED(output_drift)"

      refused_opts =
        fixture_copy(Path.join(tmp, "refused"),
          candidates: [{"sj:sourceStart 258 ;", "sj:sourceStart 259 ;"}]
        )

      never = Path.join(tmp, "never")

      {refused_output, refused_status} = run_cli(cli_args(refused_opts) ++ ["--out-dir", never])

      assert refused_status == 1
      assert refused_output =~ "REFUSED(provenance_mismatch) #{@invariant}"
      refute File.exists?(never)

      {goal_output, goal_status} =
        run_cli([
          "semantic_jira.observe_prose",
          "--admit-goal",
          "--goal",
          @friday_goal
        ])

      assert goal_status == 0, goal_output
      assert goal_output =~ "GOAL ADMITTED: "
      assert goal_output =~ ~r/\(3 GoalCheckpoints, \d+ authorities stamped\)/
    end
  end

  describe "observation authority discipline" do
    test "the observed projection contains zero work orders" do
      assert {:ok, result} = Prose.observe(fixture_opts())

      refute result.propositions_ttl =~ "WorkOrder"
      refute result.propositions_ttl =~ "sj:WorkOrder"

      admitted = RDF.Turtle.read_string!(result.propositions_ttl)
      assert instances(admitted, "WorkOrder") == []
    end

    test "every proposition is stamped UNKNOWN standing, NONE authority claim, and no digest" do
      assert {:ok, result} = Prose.observe(fixture_opts())
      admitted = RDF.Turtle.read_string!(result.propositions_ttl)

      for iri <- instances(admitted, "Proposition") do
        description = RDF.Graph.get(admitted, RDF.iri(iri))
        assert value(description, "candidateStanding") == "UNKNOWN"
        assert value(description, "authorityClaim") == "NONE"
        assert values(description, "admissionDigest") == []
      end
    end

    test "the observer writes exactly one file, propositions.ttl", %{tmp: tmp} do
      assert Prose.output_files() == ["propositions.ttl"]

      out = Path.join(tmp, "out")
      assert {:ok, result} = Prose.observe(fixture_opts())
      Prose.write!(result, out)
      assert File.ls!(out) == ["propositions.ttl"]
    end

    test "the manufacture surface is deleted from the observer module" do
      Code.ensure_loaded!(Prose)

      refute function_exported?(Prose, :compile, 1)
      refute function_exported?(Prose, :delta_kinds, 0)
      refute function_exported?(Prose, :order_iri, 2)

      # manufacture/4 was private, so it could never be exported; pinned for
      # the documentation value of stating the deletion contract in executable
      # form rather than prose.
      refute function_exported?(Prose, :manufacture, 4)
    end
  end

  ## Helpers

  defp fixture_opts(extra \\ []) do
    [
      source: Path.join(@fixture_dir, "prose.md"),
      candidates: Path.join(@fixture_dir, "candidates.ttl"),
      goal: Path.join(@fixture_dir, "goal.ttl")
    ] ++ extra
  end

  # Copies the fixture into <tmp>/test/fixtures/semantic-jira-prose/ (so the
  # candidates' repo-relative sj:sourceDocument still names the prose file)
  # and applies each {from, to} replacement exactly once, or {:append, text}.
  defp fixture_copy(tmp, mutations) do
    dir = Path.join(tmp, @fixture_dir)
    File.mkdir_p!(dir)

    for {name, key} <- [
          {"prose.md", :source},
          {"candidates.ttl", :candidates},
          {"goal.ttl", :goal}
        ] do
      content =
        Enum.reduce(
          Keyword.get(mutations, key, []),
          File.read!(Path.join(@fixture_dir, name)),
          &mutate!/2
        )

      File.write!(Path.join(dir, name), content)
    end

    [
      source: Path.join(dir, "prose.md"),
      candidates: Path.join(dir, "candidates.ttl"),
      goal: Path.join(dir, "goal.ttl")
    ]
  end

  defp mutate!({:append, text}, content), do: content <> text

  defp mutate!({from, to}, content) do
    assert String.contains?(content, from), "fixture mutation target #{inspect(from)} not found"
    String.replace(content, from, to, global: false)
  end

  defp exclusion_candidate(statement) do
    iri = Prose.proposition_iri(@ns, @source_sha, 342, 401, "Exclusion")

    """

    <#{iri}> a sj:Proposition ;
        sj:propositionKind "Exclusion" ;
        sj:statement "#{statement}" ;
        sj:sourceDocument "test/fixtures/semantic-jira-prose/prose.md" ;
        sj:sourceSha256 "#{@source_sha}" ;
        sj:sourceStart 342 ;
        sj:sourceEnd 401 ;
        sj:sourceText "Two replays of the compiler produce byte-identical outputs." ;
        sj:boundaryClass sj:FirstMile ;
        sj:requiredBy fx:GCP-1 ;
        sj:candidateStanding "UNKNOWN" ;
        sj:extractedBy "fixture:hand-authored@V23-C" .
    """
  end

  defp provenance(refusals), do: Enum.filter(refusals, &(&1.code == :provenance_mismatch))

  defp instances(graph, class) do
    graph
    |> RDF.Graph.descriptions()
    |> Enum.filter(&(RDF.iri(@sj <> class) in RDF.Description.get(&1, RDF.type(), [])))
    |> Enum.map(&RDF.IRI.to_string(&1.subject))
  end

  defp objects(graph, local) do
    graph
    |> RDF.Graph.descriptions()
    |> Enum.flat_map(&RDF.Description.get(&1, RDF.iri(@sj <> local), []))
    |> Enum.map(&to_string/1)
  end

  defp values(description, local) do
    description
    |> RDF.Description.get(RDF.iri(@sj <> local), [])
    |> Enum.map(&to_string/1)
    |> Enum.sort()
  end

  defp value(description, local) do
    case values(description, local) do
      [one] -> one
      other -> flunk("expected one sj:#{local}, got #{inspect(other)}")
    end
  end

  defp cli_args(opts) do
    [
      "semantic_jira.observe_prose",
      "--source",
      opts[:source],
      "--candidates",
      opts[:candidates],
      "--goal",
      opts[:goal]
    ]
  end

  defp run_cli(args) do
    env = [{"MIX_ENV", "test"} | Enum.map(@llm_env, &{&1, nil})]
    System.cmd("mix", args, env: env, stderr_to_stdout: true)
  end
end
