# GENERATED by ggen_igniter from priv/ggen/sensor-sink-pack/ontology.ttl.
# Do not edit. Regenerate with:
#   mix ggen_igniter.sync --pack sensor-sink-pack \
#     --out lib/ggen_igniter/stream/examples/sensor_sink.ex
#
# Manufactured threshold-crossing sensor-to-event abstraction sink, ported
# from ex4pm's reference implementation
# (~/ex4pm/apps/ex4pm_stream/lib/ex4pm/stream/sensor_sink.ex).
defmodule GgenIgniter.Stream.Examples.SensorSink do
  @moduledoc """
  Real threshold-crossing abstraction from raw numeric sensor samples into
  canonical `%Event{}` observations.

  A raw sensor reading is `{value, timestamp, sensor_id}`. An event is
  emitted only on a crossing edge of a configured threshold (value goes from
  at-or-below the threshold to strictly above it, or vice versa) -- not on
  every sample. This is the discretization step that turns a continuous
  signal into discrete process-mining events.

  Usable as a Broadway-sink-shaped callback (`handle_message/2`, taking a
  plain `%{data: reading}` map so this module carries no hard `:broadway`
  dependency -- a real `%Broadway.Message{}` struct matches this shape
  structurally), or driven synchronously via `sample/2`/`sample_all/2` for a
  plain message-handling loop.

  Regenerate via `mix ggen_igniter.sync --pack sensor-sink-pack --out
  lib/ggen_igniter/stream/examples/sensor_sink.ex`. Never hand-edit this
  file -- edit `priv/ggen/sensor-sink-pack/ontology.ttl` instead.
  """

  alias GgenIgniter.Discovery.Examples.Event, as: Event

  @type reading :: {number(), DateTime.t() | non_neg_integer(), String.t()}

  @type t :: %__MODULE__{
          threshold: number(),
          rising_activity: String.t(),
          falling_activity: String.t(),
          last_state: %{optional(String.t()) => :above | :at_or_below},
          emitted: non_neg_integer()
        }

  defstruct threshold: 0.0,
            rising_activity: "threshold_crossed_above",
            falling_activity: "threshold_crossed_below",
            last_state: %{},
            emitted: 0

  @doc "New sensor abstraction state. Options: `:threshold`, `:rising_activity`, `:falling_activity`."
  @spec new(keyword()) :: t()
  def new(opts \\ []) do
    %__MODULE__{
      threshold: Keyword.get(opts, :threshold, 0.0),
      rising_activity: Keyword.get(opts, :rising_activity, "threshold_crossed_above"),
      falling_activity: Keyword.get(opts, :falling_activity, "threshold_crossed_below")
    }
  end

  @doc """
  Fold one raw sample into the abstraction state. Returns `{new_state, event_or_nil}`
  -- `nil` when the sample did not cross the threshold (the common case: most raw
  samples are abstraction-irrelevant noise around a steady state).
  """
  @spec sample(t(), reading()) :: {t(), Event.t() | nil}
  def sample(%__MODULE__{} = state, {value, timestamp, sensor_id}) do
    band = if value > state.threshold, do: :above, else: :at_or_below

    case Map.fetch(state.last_state, sensor_id) do
      {:ok, ^band} ->
        {state, nil}

      {:ok, :at_or_below} when band == :above ->
        emit(state, sensor_id, timestamp, value, state.rising_activity)

      {:ok, :above} when band == :at_or_below ->
        emit(state, sensor_id, timestamp, value, state.falling_activity)

      :error ->
        {%{state | last_state: Map.put(state.last_state, sensor_id, band)}, nil}
    end
  end

  @doc "Fold a real sequence of raw samples, returning the final state and the ordered list of abstracted events."
  @spec sample_all(t(), [reading()]) :: {t(), [Event.t()]}
  def sample_all(%__MODULE__{} = state, readings) when is_list(readings) do
    {final_state, events_rev} =
      Enum.reduce(readings, {state, []}, fn reading, {acc_state, acc_events} ->
        case sample(acc_state, reading) do
          {new_state, nil} -> {new_state, acc_events}
          {new_state, event} -> {new_state, [event | acc_events]}
        end
      end)

    {final_state, Enum.reverse(events_rev)}
  end

  @doc """
  Broadway-sink-shaped message handler: unwraps a `%{data: reading}` map
  (structurally matching a real `%Broadway.Message{}`), abstracts it against
  the state held in `context`, and forwards any emitted event to
  `context.forward.(event)`.
  """
  @spec handle_message(%{data: reading()}, %{
          sink_state: pid() | t(),
          forward: (Event.t() -> any())
        }) ::
          %{data: reading()}
  def handle_message(%{data: reading} = message, %{
        sink_state: state,
        forward: forward
      })
      when is_function(forward, 1) do
    case sample(state, reading) do
      {_new_state, nil} -> :ok
      {_new_state, event} -> forward.(event)
    end

    message
  end

  defp emit(state, sensor_id, timestamp, value, activity) do
    event = %Event{
      id: "sensor:#{sensor_id}:#{state.emitted}",
      activity: activity,
      timestamp: timestamp,
      object_ids: [sensor_id],
      relationships: [],
      attributes: %{value: value}
    }

    new_state = %{
      state
      | last_state: Map.put(state.last_state, sensor_id, band_of(state, value)),
        emitted: state.emitted + 1
    }

    {new_state, event}
  end

  defp band_of(state, value), do: if(value > state.threshold, do: :above, else: :at_or_below)
end
