defmodule Mix.Tasks.GgenIgniter.HandAuthored do
  # These CLI exit helpers all end in `System.halt/1`, which never returns to
  # the caller by design (real process exit codes for `--help`/invalid
  # invocation/law-refusal/blocked-render outcomes -- the same contract as
  # `Mix.Tasks.GgenIgniter.Doctor`). Dialyzer correctly observes each has no
  # local return and flags it `:no_return`; that is the intended contract
  # here, not a bug -- suppress per-function rather than leave it as an
  # unexplained "known" warning.
  @dialyzer {:no_return, print_help_and_halt: 0}
  @dialyzer {:no_return, invalid_invocation_and_halt: 2}
  @dialyzer {:no_return, refused_and_halt: 2}
  @dialyzer {:no_return, blocked_render_and_halt: 1}

  @moduledoc """
  The hand-authored-source admission task:
  `mix ggen_igniter.hand_authored <verb>` with verbs `admit`, `list`, `check`.

  Automates the exact admission law the `beam4pm-process-model-pack` (v0.1.10+)
  expresses as `bpm:HandAuthoredSource` / `bpm:AuthorshipKind` facts and
  enforces with gates `050`/`060`/`070` (`gates/*.rq`) plus the consumer's
  rendered `scripts/gate_authorship_check.sh`: every file under a manufactured
  root that carries no `GENERATED by ggen` marker is an ADMITTED, COUNTED
  exception, or the tree is refused. Every v26.9.18 parity agent performed
  this admission BY HAND in lockstep (edit ontology.ttl, get the sha wrong,
  trip REFUSED_SHA_DRIFT / REFUSED_UNADMITTED / a ceiling, re-render, rerun
  the gate); this task retires that lockstep by performing the whole lawful
  admission mechanically, validating every capability-object law BEFORE any
  byte is written.

  ## Verbs

      mix ggen_igniter.hand_authored admit --file lib/beam4pm_dfcm.ex \\
          --kind native_engine_facade \\
          --reason "why manufacturing this file is currently disproportionate" \\
          --principal "Sean Chatman (repo owner) via <session/agent>" \\
          --acceptance-command "mix test test/beam4pm_dfcm_test.exs" \\
          --sunset-plan "render from pack facts; then delete this admission" \\
          [--expires 2026-12-31] [--admitted-at-commit abc1234]
          [--acceptance-prerequisite path-or-cmd:...] [--no-render]

      mix ggen_igniter.hand_authored list   [--ontology ...] [--pack-dir ...]

      mix ggen_igniter.hand_authored check  [--gate-script scripts/gate_authorship_check.sh]

  ### `admit`

  Validates, in order (cheapest, highest-information gate first), and refuses
  with a typed one-line `REFUSED_*` code + exit 1 on the first failure:

  1. `REFUSED_ONTOLOGY_NOT_FOUND` / `REFUSED_PACK_ONTOLOGY_NOT_FOUND` -- the
     consumer's `ontology.ttl` (default `./ontology.ttl`) / the pack's
     ontology (default
     `vendor/ggen-marketplace/packs/beam4pm-process-model-pack/ontology.ttl`)
     must exist.
  2. `REFUSED_FILE_NOT_FOUND` -- the admitted file must exist on disk (the
     sha256 is computed over the REAL bytes, never asserted).
  3. `REFUSED_MARKED_FILE` -- the file's first 3 lines must NOT carry the
     `GENERATED by ggen` marker (admitting a manufactured file is the gate's
     REFUSED_CONTRADICTION, caught before it can be committed).
  4. `REFUSED_MISSCOPED` -- the path must sit under a manufactured root
     (`src lib gleam/src gleam/test test schema docs/reference
     infra/gcp/cloudrun infra/gcp/packer`, the gate script's own ROOTS list;
     `--roots` overrides).
  5. `REFUSED_MISSING_ACCEPTANCE_COMMAND` -- every admission needs a real
     acceptance command (gate 050 requires `bpm:acceptanceCommand` for ALL
     kinds, debt or not).
  6. `REFUSED_INVALID_EXPIRY` -- `--expires` must be `YYYY-MM-DD` when given
     (the manifest renders the raw literal; the shell gate string-compares it
     against today).
  7. `REFUSED_UNKNOWN_KIND` -- `--kind` must name an admitted
     `bpm:AuthorshipKind` in the PACK's closed vocabulary (anti-join law of
     gate 060, evaluated here before writing, not after).
  8. `REFUSED_MISSING_SUNSET_PLAN` / `REFUSED_MISSING_EXPIRY` -- kinds whose
     `bpm:countsAsDebt` is `"true"` must carry `--sunset-plan` and `--expires`
     (gate 050: a path-only debt admission is a standing grant).
  9. `REFUSED_DUPLICATE_SOURCE_PATH` -- no existing `bpm:HandAuthoredSource`
     individual may already admit the same `bpm:sourcePath` (gate 060's
     duplicate law; a duplicate would double-count the debt).
  10. `REFUSED_CEILING_EXCEEDED` -- the kind's current admitted count + 1 must
      not exceed its `bpm:debtCeiling` (gate 070's law, with the pack-edit
      remedy named: raising a ceiling is a reviewed edit to the PACK's
      ontology.ttl, never an ambient grant).
  11. `REFUSED_MISSING_FIELD` -- `--principal`, `--reason`, and an admitted-at
      commit (`--admitted-at-commit` or `git rev-parse --short HEAD` in the
      consumer tree) must all resolve (gate 050's required-field set).
  12. `REFUSED_ONTOLOGY_UNPARSEABLE` -- both ontologies must parse as real
      Turtle; `REFUSED_SUBJECT_PREFIX_UNDECLARED` -- the subject namespace
      prefix (default `bap`, `--subject-prefix`) must already be declared in
      the consumer ontology.

  Only then is the new individual appended to the consumer's ontology.ttl --
  directly after the LAST existing `bpm:HandAuthoredSource` individual (or at
  end-of-file when the graph admits none yet; Turtle `@prefix` declarations
  are positional, and both anchors are after the consumer's own prefix
  declarations). The write is a single `File.write!` of the full modified
  content (the same direct-write contract `GgenIgniter.DoctorFixes` uses; see
  its `--dry-run` note). The individual carries exactly the capability-object
  fields the gates require: debt kinds get `bpm:contentSha256` (lowercase hex
  over the real bytes), `bpm:admissionExpires`, `bpm:sunsetPlan`; non-debt
  kinds get none of the three (the manifest renders `-`, matching the
  consumer convention for `manufacturing_input` / `reference_evidence` rows).

  Then, unless `--no-render` was passed, the pack render is triggered: the
  three hand-authored projections
  (`schema/beam4pm_hand_authored_source.tsv`, `docs/reference/
  beam4pm_hand_authored_source.md`, `test/beam4pm_authorship_gate_test.exs`)
  are Tera templates rendered by the Rust `ggen sync run` (NOT
  `mix ggen_igniter.sync` -- that is the EEx/Ash leg and renders none of
  these). Because none of the three templates carries `force: true`, ggen's
  write policy (FM-WRITE-005) refuses to overwrite an existing target, so the
  task applies the same procedure the v26.9.18 integration used and
  documented in its synthesis commit: temporarily scaffold `force: true` into
  the three templates' front matter, run `ggen sync run`, then restore the
  template bytes verbatim (a failed restore is
  `RENDER_TEMPLATE_RESTORE_FAILED`, exit 1). If the `ggen` binary is not on
  PATH the admission itself still stands (ontology.ttl is already written)
  and the task prints the exact two-step commands instead --
  `BLOCKED_RENDER_NO_GGEN`, exit 3. If ggen refuses on a pack-content-hash
  mismatch (FM-PACK-008: the ceilings were just raised in the vendored pack),
  its own remediation is `rm -f ggen.lock && ggen sync run` (re-lock) --
  printed verbatim on failure, never attempted silently.

  Under the global `--dry-run`, NOTHING is written and nothing is rendered:
  every validation above still really runs, and the task prints the individual
  it WOULD append (with its real sha256) plus `DRY-RUN: no files written`.

  ### `list`

  Loads consumer + pack ontologies, prints the admitted set grouped per kind
  (count / ceiling, `AT CEILING` flagged), one row per admission (path, kind,
  debt, sha-bound, expiry), then really runs the pack's own gate queries
  `050`/`060`/`070` (`gates/*.rq`) through the oxigraph engine over the merged
  consumer+pack graph. Exit 1 iff any gate query returns a row (the graph
  itself violates the law) -- this is the pre-render, pre-shell-gate
  half of `check`, usable against the graph alone.

  ### `check`

  Runs the consumer's rendered shell gate (default
  `scripts/gate_authorship_check.sh`) as a real subprocess against the real
  tree, streaming its output, and exits with the gate's own exit code. This is
  the decisive, observed gate: manifest vs `git ls-files`, sha drift, expiry,
  acceptance exercise (`--exercise` is the gate script's own flag; pass it via
  `--gate-arg`).

  ## Exit codes

  - `0` -- admit/list/check succeeded (under `admit --dry-run`: validated,
    nothing written).
  - `1` -- a typed `REFUSED_*` law refusal (nothing was written), a gate row
    from `list`, a failing `check` gate, or a failed template restore.
  - `2` -- invalid invocation: unknown verb, unknown flag, missing
    `--file`/`--kind`, or a verb omitted.
  - `3` -- unsupported capability on this host: render requested but the
    `ggen` binary is absent (the two-step manual commands are printed).
  """

  use Igniter.Mix.Task

  alias GgenIgniter.Query.Oxigraph

  @verbs ~w(admit list check)

  @impl Igniter.Mix.Task
  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      group: :ggen_igniter,
      example:
        "mix ggen_igniter.hand_authored admit --file lib/beam4pm_dfcm.ex --kind native_engine_facade",
      positional: [],
      schema: [
        file: :string,
        kind: :string,
        reason: :string,
        principal: :string,
        sunset_plan: :string,
        expires: :string,
        acceptance_command: :string,
        acceptance_prerequisite: :string,
        admitted_at_commit: :string,
        subject_prefix: :string,
        ontology: :string,
        pack_ontology: :string,
        pack_dir: :string,
        gate_script: :string,
        gate_arg: :string,
        roots: :string,
        render: :boolean,
        json: :boolean,
        help: :boolean,
        version: :boolean
      ],
      aliases: [h: :help, v: :version],
      required: []
    }
  end

  @known_flags ~w(--file --kind --reason --principal --sunset-plan --expires
                  --acceptance-command --acceptance-prerequisite --admitted-at-commit
                  --subject-prefix --ontology --pack-ontology --pack-dir --gate-script
                  --gate-arg --roots --no-render --render --json --no-json
                  --help --version -h -v
                  --dry-run --no-dry-run --yes --no-yes
                  --check --no-check --scribe --from-igniter-new
                  --no-from-igniter-new --igniter-repeat --no-igniter-repeat
                  --no-no-color)

  @impl Mix.Task
  def run(argv) do
    cond do
      "--help" in argv or "-h" in argv ->
        print_help_and_halt()

      # Pre-validate unknown flags BEFORE `super/1`: Igniter.Mix.Task's
      # generated runner validates argv against info/2's schema with
      # OptionParser's :strict mode, which raises a Mix.Error ("Unknown
      # option") that Mix's own handler reports with exit code 1 -- this
      # task's contract reserves exit 2 for invalid invocation, and the
      # check must happen here (inside igniter/1 is too late: the strict
      # parse has already raised before igniter/1 gets control). Same
      # shape as Mix.Tasks.GgenIgniter.Doctor's run/1.
      (bad = first_unknown_flag(argv)) != nil ->
        invalid_invocation_and_halt("unknown flag #{bad}", [])

      true ->
        super(argv)
    end
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    argv = igniter.args.argv
    opts = igniter.args.options

    verb =
      argv
      |> Enum.reject(&String.starts_with?(&1, "-"))
      |> case do
        [verb | _] -> verb
        [] -> nil
      end

    cond do
      opts[:version] ->
        print_version_and_halt()

      verb == nil ->
        invalid_invocation_and_halt(
          "no verb given -- one of #{Enum.join(@verbs, " | ")} (try --help)",
          opts
        )

      verb not in @verbs ->
        invalid_invocation_and_halt(
          "unknown verb #{inspect(verb)} -- one of #{Enum.join(@verbs, " | ")}",
          opts
        )

      verb == "admit" ->
        run_admit(igniter, opts)

      verb == "list" ->
        run_list(igniter, opts)

      verb == "check" ->
        run_check(igniter, opts)
    end
  end

  # ===========================================================================
  # admit
  # ===========================================================================

  # The admit verb is a validation pipeline: every stage either returns its
  # inputs for the next stage or halts with a typed refusal. Splitting the
  # stages keeps each unit under the complexity ceiling without weakening a
  # single check (v26.9.22 refactor; behavior is byte-identical).
  defp run_admit(igniter, opts) do
    root = File.cwd!()

    ontology_path = Path.expand(opts[:ontology] || default_ontology())
    pack_ontology_path = Path.expand(opts[:pack_ontology] || default_pack_ontology(opts))
    pack_dir = Path.expand(opts[:pack_dir] || default_pack_dir())

    validate_admit_paths!(ontology_path, pack_ontology_path)
    rel_path = validate_admit_target!(relative_admitted_path(opts[:file], root), opts)
    merged = load_admit_graphs(ontology_path, pack_ontology_path)
    {kind, kind_name, count} = validate_admit_kind!(merged, opts, pack_ontology_path)
    validate_admit_capacity!(merged, rel_path, kind, kind_name)

    sha = sha256_file!(rel_path)
    committed = validate_admission_fields!(opts, root, ontology_path)
    prefix = opts[:subject_prefix] || "bap"

    individual =
      build_admit_individual(merged, opts, %{
        rel_path: rel_path,
        kind: kind,
        kind_name: kind_name,
        count: count,
        sha: sha,
        committed: committed,
        prefix: prefix
      })

    content = File.read!(ontology_path)
    {new_content, anchor} = insert_individual(content, individual)

    if opts[:dry_run] == true do
      report_admit_dry_run(igniter, individual, ontology_path, rel_path, sha)
    else
      File.write!(ontology_path, new_content)

      report_admission(igniter, opts, %{
        individual: individual,
        rel_path: rel_path,
        kind: kind,
        kind_name: kind_name,
        count: count,
        sha: sha,
        committed: committed,
        root: root,
        pack_dir: pack_dir,
        ontology_path: ontology_path,
        anchor: anchor
      })
    end
  end

  defp validate_admit_paths!(ontology_path, pack_ontology_path) do
    cond do
      not File.exists?(ontology_path) ->
        refused_and_halt("REFUSED_ONTOLOGY_NOT_FOUND", ontology_path)

      not File.exists?(pack_ontology_path) ->
        refused_and_halt("REFUSED_PACK_ONTOLOGY_NOT_FOUND", pack_ontology_path)

      true ->
        :ok
    end
  end

  defp validate_admit_target!(rel_path, opts) do
    cond do
      is_nil(rel_path) ->
        invalid_invocation_and_halt("admit requires --file <path>", opts)

      not File.regular?(rel_path) ->
        refused_and_halt("REFUSED_FILE_NOT_FOUND", rel_path)

      marked?(rel_path) ->
        refused_and_halt(
          "REFUSED_MARKED_FILE",
          "#{rel_path} carries the 'GENERATED by ggen' marker in its first 3 lines -- " <>
            "a manufactured file is the gate's REFUSED_CONTRADICTION, never an admission"
        )

      not in_scope?(rel_path, roots(opts)) ->
        refused_and_halt(
          "REFUSED_MISSCOPED",
          "#{rel_path} is not under any manufactured root: #{Enum.join(roots(opts), " ")}"
        )

      blank?(opts[:acceptance_command]) ->
        refused_and_halt(
          "REFUSED_MISSING_ACCEPTANCE_COMMAND",
          "every admission carries bpm:acceptanceCommand (gate 050) -- pass --acceptance-command"
        )

      match?({:invalid, _}, expiry(opts)) ->
        {:invalid, value} = expiry(opts)

        refused_and_halt(
          "REFUSED_INVALID_EXPIRY",
          "--expires #{inspect(value)} is not YYYY-MM-DD (the shell gate string-compares it)"
        )

      true ->
        :ok
    end

    rel_path
  end

  defp load_admit_graphs(ontology_path, pack_ontology_path) do
    pack_graph = parse_graph!(pack_ontology_path, :pack)
    consumer_graph = parse_graph!(ontology_path, :consumer)
    RDF.Data.merge(pack_graph, consumer_graph)
  end

  # Kind resolution + the debt-law checks (closed vocabulary gate 060, sunset
  # plan and expiry for debt kinds per gate 050). Returns {kind, name, count}.
  defp validate_admit_kind!(merged, opts, pack_ontology_path) do
    kind_name = opts[:kind]

    if blank?(kind_name) do
      invalid_invocation_and_halt("admit requires --kind <authorship-kind-name>", opts)
    end

    kind = resolve_kind(merged, kind_name)

    unless kind do
      refused_and_halt(
        "REFUSED_UNKNOWN_KIND",
        "#{inspect(kind_name)} is not an admitted bpm:AuthorshipKind in #{pack_ontology_path} " <>
          "-- the vocabulary is CLOSED (gate 060); adding a member is a reviewed pack edit"
      )
    end

    validate_debt_law!(kind, kind_name, opts)
    {kind, kind_name, kind_count(merged, kind.iri)}
  end

  defp validate_debt_law!(kind, kind_name, opts) do
    if kind.debt and blank?(opts[:sunset_plan]) do
      refused_and_halt(
        "REFUSED_MISSING_SUNSET_PLAN",
        "kind #{kind_name} counts as manufacturing debt -- a debt admission must carry " <>
          "bpm:sunsetPlan (gate 050: a path-only debt admission is a standing grant)"
      )
    end

    if kind.debt and is_nil(expiry(opts)) do
      refused_and_halt(
        "REFUSED_MISSING_EXPIRY",
        "kind #{kind_name} counts as manufacturing debt -- a debt admission must carry " <>
          "bpm:admissionExpires (gate 050), e.g. --expires 2026-12-31"
      )
    end
  end

  defp validate_admit_capacity!(merged, rel_path, kind, kind_name) do
    existing_paths = admitted_paths(merged)

    if Map.has_key?(existing_paths, rel_path) do
      refused_and_halt(
        "REFUSED_DUPLICATE_SOURCE_PATH",
        "#{rel_path} is already admitted (gate 060) -- re-admitting a drifted file means " <>
          "editing its existing individual's bpm:contentSha256, not adding a second one"
      )
    end

    count = kind_count(merged, kind.iri)

    if count + 1 > kind.ceiling do
      refused_and_halt(
        "REFUSED_CEILING_EXCEEDED",
        "kind #{kind_name} would hold #{count + 1} admitted files against its " <>
          "bpm:debtCeiling #{kind.ceiling} (gate 070) -- raising a ceiling is a reviewed edit " <>
          "to the PACK's ontology.ttl, never an ambient grant"
      )
    end
  end

  # Commit identity + principal/reason/prefix field checks (gate 050).
  defp validate_admission_fields!(opts, root, ontology_path) do
    committed =
      opts[:admitted_at_commit] || git_head_short(root) ||
        refused_and_halt(
          "REFUSED_MISSING_FIELD",
          "bpm:admittedAtCommit could not be resolved -- not a git tree? pass --admitted-at-commit"
        )

    blank?(opts[:principal]) &&
      refused_and_halt(
        "REFUSED_MISSING_FIELD",
        "bpm:authorizingPrincipal is required (gate 050) -- pass --principal"
      )

    blank?(opts[:reason]) &&
      refused_and_halt(
        "REFUSED_MISSING_FIELD",
        "bpm:admissionReason is required (gate 050) -- pass --reason"
      )

    prefix = opts[:subject_prefix] || "bap"

    unless prefix_declared?(File.read!(ontology_path), prefix) do
      refused_and_halt(
        "REFUSED_SUBJECT_PREFIX_UNDECLARED",
        "@prefix #{prefix}: is not declared in #{ontology_path} -- declare it or pass --subject-prefix"
      )
    end

    committed
  end

  defp build_admit_individual(merged, opts, bounds) do
    %{
      subject: subject_for(merged, bounds.prefix, bounds.rel_path),
      path: bounds.rel_path,
      kind_iri: bounds.kind.iri,
      kind_name: bounds.kind_name,
      principal: opts[:principal],
      reason: opts[:reason],
      acceptance_command: opts[:acceptance_command],
      acceptance_prerequisite: opts[:acceptance_prerequisite],
      sha: bounds.sha,
      debt: bounds.kind.debt,
      admitted_at: bounds.committed,
      expires: expiry(opts),
      sunset_plan: opts[:sunset_plan]
    }
  end

  defp report_admit_dry_run(igniter, individual, ontology_path, rel_path, sha) do
    IO.puts(
      "DRY-RUN: validations passed; would append #{individual.subject} to #{ontology_path}:"
    )

    IO.puts(indent(ttl_block(individual), "    "))
    IO.puts("DRY-RUN: no files written, nothing rendered")

    Igniter.add_notice(
      igniter,
      "ggen_igniter.hand_authored admit: dry-run OK -- #{rel_path} would be admitted (sha256 #{sha})"
    )
  end

  defp report_admission(igniter, opts, b) do
    IO.puts("✔ ADMITTED: #{b.rel_path}")

    IO.puts(
      "    kind: #{b.kind_name} (#{if b.kind.debt, do: "debt", else: "not debt"}) " <>
        "count #{b.count + 1}/#{b.kind.ceiling}#{if b.count + 1 == b.kind.ceiling, do: "  [AT CEILING]"}"
    )

    if b.kind.debt do
      IO.puts("    sha256: #{b.sha}")
      IO.puts("    expires: #{expiry(opts)}   admittedAt: #{b.committed}")
    end

    IO.puts("    ontology: #{b.anchor} -> #{b.ontology_path}")

    case admit_render(b.root, b.pack_dir, opts) do
      :skipped ->
        IO.puts("– render skipped (--no-render); the manifest is STALE until you run:")
        IO.puts("    ggen sync run    # from #{b.root}")
        IO.puts("next: mix ggen_igniter.hand_authored check")

      {:ok, scaffolded} ->
        IO.puts(
          "✔ RENDER: ggen sync run exit 0 (#{scaffolded} template(s) force-scaffolded, restored)"
        )

        IO.puts("next: mix ggen_igniter.hand_authored check")

      {:blocked, message} ->
        blocked_render_and_halt(message)

      {:error, message} ->
        refused_and_halt("RENDER_FAILED", message)
    end

    Igniter.add_notice(
      igniter,
      "ggen_igniter.hand_authored admit: #{b.rel_path} admitted as #{b.kind_name} (sha256 #{b.sha})"
    )
  end

  defp admit_render(root, pack_dir, opts) do
    if opts[:render] == false, do: :skipped, else: render(root, pack_dir)
  end

  # ===========================================================================
  # list
  # ===========================================================================

  defp run_list(igniter, opts) do
    ontology_path = Path.expand(opts[:ontology] || default_ontology())
    pack_dir = Path.expand(opts[:pack_dir] || default_pack_dir())
    pack_ontology_path = Path.expand(opts[:pack_ontology] || default_pack_ontology(opts))

    validate_list_paths!(ontology_path, pack_ontology_path)

    pack_graph = parse_graph!(pack_ontology_path, :pack)
    consumer_graph = parse_graph!(ontology_path, :consumer)
    merged = RDF.Data.merge(pack_graph, consumer_graph)

    kinds = all_kinds(merged)
    counts = Map.new(kinds, fn kind -> {kind.iri, kind_count(merged, kind.iri)} end)
    rows = admitted_rows(merged)

    print_list_header(ontology_path, pack_ontology_path, rows)
    print_list_kinds(kinds, counts)
    print_list_rows(rows)

    gate_rows = evaluate_list_gates(merged, pack_dir)
    report_list_gates(igniter, gate_rows, length(rows))
  end

  defp validate_list_paths!(ontology_path, pack_ontology_path) do
    cond do
      not File.exists?(ontology_path) ->
        refused_and_halt("REFUSED_ONTOLOGY_NOT_FOUND", ontology_path)

      not File.exists?(pack_ontology_path) ->
        refused_and_halt("REFUSED_PACK_ONTOLOGY_NOT_FOUND", pack_ontology_path)

      true ->
        :ok
    end
  end

  defp print_list_header(ontology_path, pack_ontology_path, rows) do
    total = length(rows)
    debt_n = Enum.count(rows, & &1.debt)

    IO.puts("== ggen_igniter.hand_authored list ==")
    IO.puts("ontology: #{ontology_path}")
    IO.puts("pack:     #{pack_ontology_path}")
    IO.puts("admitted: #{total} (#{debt_n} counted as manufacturing debt)")
  end

  defp print_list_kinds(kinds, counts) do
    IO.puts(
      Enum.map_join(
        kinds,
        "\n",
        fn kind ->
          n = Map.get(counts, kind.iri, 0)
          at = if n >= kind.ceiling, do: "  [AT CEILING]", else: ""

          "  #{String.pad_trailing(kind.name, 32)} debt=#{pad(kind.debt)}  #{n}/#{kind.ceiling}#{at}"
        end
      )
    )
  end

  defp print_list_rows(rows) do
    IO.puts("rows:")

    Enum.each(rows, fn row ->
      sha = row.sha || "-"

      IO.puts(
        "  #{row.path}  #{row.kind}  debt=#{pad(row.debt)}  sha=#{String.slice(sha, 0, 12)}  " <>
          "expires=#{row.expires || "-"}"
      )
    end)
  end

  defp evaluate_list_gates(merged, pack_dir) do
    pack_dir
    |> gate_queries()
    |> Enum.map(fn {name, path} ->
      {name, path, length(Oxigraph.run(merged, File.read!(path)))}
    end)
  end

  defp report_list_gates(igniter, gate_rows, total) do
    IO.puts("pack gates (oxigraph over merged consumer+pack graph):")

    Enum.each(gate_rows, fn {name, _path, n} ->
      IO.puts("  #{String.pad_trailing(name, 44)} #{n} row(s)")
    end)

    bad = Enum.filter(gate_rows, fn {_n, _p, count} -> count > 0 end)

    case bad do
      [] ->
        IO.puts("LIST: OK -- #{total} admitted, 0 gate rows")

        Igniter.add_notice(
          igniter,
          "ggen_igniter.hand_authored list: OK (#{total} admitted, 0 gate rows)"
        )

      violations ->
        Enum.each(violations, fn {name, _path, count} ->
          IO.puts("✘ gate #{name}: #{count} refusing row(s)")
        end)

        IO.puts("LIST: FAIL -- the graph itself violates the admission law (fix before render)")
        System.halt(1)
    end
  end

  # ===========================================================================
  # check
  # ===========================================================================

  defp run_check(igniter, opts) do
    gate_script = Path.expand(opts[:gate_script] || "scripts/gate_authorship_check.sh")

    unless File.exists?(gate_script) do
      refused_and_halt(
        "REFUSED_GATE_SCRIPT_NOT_FOUND",
        "#{gate_script} -- render it first (ggen sync run) or pass --gate-script"
      )
    end

    args = [gate_script] ++ if opts[:gate_arg] in [nil, ""], do: [], else: [opts[:gate_arg]]

    # System.cmd with `into:` returns {collector_value, exit_status}; the
    # IO.stream() collector keeps the gate's own output live on our stdio and
    # the gate's real exit code is what this verb exits with.
    {_collector, status} =
      System.cmd("bash", args,
        cd: File.cwd!(),
        into: IO.stream(:stdio, :line),
        stderr_to_stdout: true
      )

    if status == 0 do
      Igniter.add_notice(igniter, "ggen_igniter.hand_authored check: gate PASSED (exit 0)")
    else
      IO.puts("✘ ggen_igniter.hand_authored check: gate FAILED (exit #{status})")
      System.halt(status)
    end
  end

  # ===========================================================================
  # render (the two-step documented, mechanically performed)
  # ===========================================================================

  # The three hand-authored projections are Tera templates on the Rust ggen
  # leg. None carries `force: true`, and FM-WRITE-005 refuses to overwrite an
  # existing target from a non-force template, so re-rendering over an
  # existing manifest needs the force scaffold the v26.9.18 integration
  # documented and used: scaffold -> `ggen sync run` -> restore verbatim.
  #
  # The scaffold changes the PACK's content bytes, so a consumer with a
  # ggen.lock would trip FM-PACK-008 (pack content hash mismatch) -- observed
  # for real on the beam4pm replay. FM-PACK-008's own remediation is
  # "delete ggen.lock to intentionally re-lock", so the render leg performs
  # the same dance the integration did: back up ggen.lock, remove it, sync
  # (scaffolded), restore the templates AND the original lock byte-for-byte,
  # then run `ggen sync run` once more against the CLEAN pack -- which
  # re-validates the original lock and proves the render idempotent.
  @hand_authored_templates ~w(
    beam4pm_hand_authored_source.tsv.tmpl
    beam4pm_hand_authored_source.md.tmpl
    beam4pm_authorship_gate_test.exs.tmpl
  )

  defp render(root, pack_dir) do
    if is_nil(System.find_executable("ggen")) do
      {:blocked,
       "the `ggen` binary is not on PATH -- the admission is written to ontology.ttl; " <>
         "finish by hand (two-step):\n" <>
         "    (1) temporarily add `force: true` after the opening `---` of the three " <>
         "hand-authored templates in #{Path.join(pack_dir, "templates")}\n" <>
         "    (2) cd #{root} && ggen sync run   (then restore the templates)\n" <>
         "    alternative: re-run admit with --no-render, render by hand, then " <>
         "mix ggen_igniter.hand_authored check"}
    else
      templates =
        @hand_authored_templates
        |> Enum.map(&Path.join([pack_dir, "templates", &1]))
        |> Enum.filter(&File.exists?/1)

      case templates do
        [] ->
          {:error, "no hand-authored templates found under #{Path.join(pack_dir, "templates")}"}

        templates ->
          render_with_templates(root, pack_dir, templates)
      end
    end
  end

  defp render_with_templates(root, _pack_dir, templates) do
    lock_path = Path.join(root, "ggen.lock")
    lock_backup = lock_backup(lock_path)
    scaffolded = scaffold_templates(templates)

    # -- first sync: scaffolded pack, lock intentionally removed so the
    #    scaffolded content cannot trip FM-PACK-008 -----------------------
    if lock_backup, do: File.rm(lock_path)

    {output1, status1} = sync_run(root)

    cond do
      restore_failure = template_restore_failure(scaffolded) ->
        restore_failure

      status1 != 0 ->
        restore_lock(lock_path, lock_backup)
        {:error, sync_tail("scaffolded render", status1, output1)}

      true ->
        restore_lock(lock_path, lock_backup)
        idempotence_sync(root, length(scaffolded))
    end
  end

  # nil = no lock existed (fresh consumer); binary = lock bytes to preserve
  defp lock_backup(lock_path) do
    if File.exists?(lock_path), do: File.read!(lock_path)
  end

  # -- scaffold: add force: true to templates that lack it --------------
  defp scaffold_templates(templates) do
    templates
    |> Enum.map(&maybe_scaffold/1)
    |> Enum.reject(&is_nil/1)
  end

  defp maybe_scaffold(path) do
    original = File.read!(path)

    if scaffold_needed?(original) do
      File.write!(path, scaffold_force(original))
      {path, original}
    else
      nil
    end
  end

  defp template_restore_failure(scaffolded) do
    case restore_templates(scaffolded) do
      :ok ->
        nil

      {:error, path} ->
        {:error, "RENDER_TEMPLATE_RESTORE_FAILED: #{path} did not restore byte-identically"}
    end
  end

  defp restore_templates(scaffolded) do
    Enum.reduce_while(scaffolded, :ok, fn {path, original}, :ok ->
      File.write!(path, original)
      verify_restored(path, original)
    end)
  end

  defp verify_restored(path, original) do
    if File.read!(path) == original, do: {:cont, :ok}, else: {:halt, {:error, path}}
  end

  # Restore the ORIGINAL lock: nil removes a lock the scaffolded sync
  # created (pinning the scaffolded hash, which would mask a later real
  # re-lock), binary restores the consumer's own lock bytes verbatim.
  defp restore_lock(lock_path, nil), do: if(File.exists?(lock_path), do: File.rm(lock_path))
  defp restore_lock(lock_path, backup) when is_binary(backup), do: File.write!(lock_path, backup)
  defp restore_lock(_lock_path, _other), do: :ok

  defp sync_run(root) do
    System.cmd("ggen", ["sync", "run", "--format", "quiet"], cd: root, stderr_to_stdout: true)
  end

  # -- second sync: templates + original lock restored; the clean pack
  #    re-validates against the original lock and the render is proven
  #    idempotent -----------------------------------------------------------
  defp idempotence_sync(root, scaffolded_count) do
    {output2, status2} = sync_run(root)

    if status2 == 0 do
      {:ok, scaffolded_count}
    else
      {:error, sync_tail("post-restore idempotence check", status2, output2)}
    end
  end

  defp sync_tail(phase, status, output) do
    "ggen sync run exit #{status} (#{phase}). tail:\n" <>
      indent(String.slice(output, -2_000, 2_000), "    ")
  end

  defp scaffold_needed?(content) do
    case String.split(content, "\n", parts: 3) do
      ["---", second | _] -> not String.contains?(second, "force:")
      _ -> false
    end
  end

  defp scaffold_force(content) do
    case String.split(content, "\n", parts: 2) do
      [first, rest] -> first <> "\nforce: true\n" <> rest
      [first] -> first <> "\nforce: true\n"
    end
  end

  # ===========================================================================
  # graph law helpers
  # ===========================================================================

  defp parse_graph!(path, which) do
    RDF.Turtle.read_file!(path)
  rescue
    e ->
      refused_and_halt(
        "REFUSED_ONTOLOGY_UNPARSEABLE",
        "#{which} ontology #{path}: #{Exception.message(e)}"
      )
  end

  @kind_query """
  PREFIX bpm: <https://ggen.dev/ontology/beam-process-model#>
  SELECT ?kind ?name ?debt ?ceiling WHERE {
    ?kind a bpm:AuthorshipKind ;
          bpm:authorshipKindName ?name ;
          bpm:countsAsDebt ?debt ;
          bpm:debtCeiling ?ceiling .
  }
  """

  defp all_kinds(merged) do
    Oxigraph.run(merged, @kind_query)
    |> Enum.map(fn row ->
      %{
        iri: cell(row, "kind"),
        name: cell(row, "name"),
        debt: cell(row, "debt") == "true",
        ceiling: int_cell(row, "ceiling")
      }
    end)
  end

  defp resolve_kind(merged, name) do
    merged |> all_kinds() |> Enum.find(&(&1.name == name))
  end

  @admitted_query """
  PREFIX bpm: <https://ggen.dev/ontology/beam-process-model#>
  SELECT ?h ?path ?kind ?sha ?expires ?debt WHERE {
    ?h a bpm:HandAuthoredSource ;
       bpm:sourcePath ?path ;
       bpm:authorshipKind ?kind .
    ?kind bpm:authorshipKindName ?kindname ;
          bpm:countsAsDebt ?debt .
    OPTIONAL { ?h bpm:contentSha256 ?sha }
    OPTIONAL { ?h bpm:admissionExpires ?expires }
  }
  """

  defp admitted_rows(merged) do
    Oxigraph.run(merged, @admitted_query)
    |> Enum.map(fn row ->
      %{
        path: cell(row, "path"),
        kind: cell(row, "kindname"),
        debt: cell(row, "debt") == "true",
        sha: cell_opt(row, "sha"),
        expires: cell_opt(row, "expires")
      }
    end)
    |> Enum.sort_by(& &1.path)
  end

  # A plain map of path -> true: MapSet.new/1 over a map would wrap the
  # {path, true} TUPLES into the set, and a string path could never match one
  # -- the duplicate check would silently never fire.
  defp admitted_paths(merged) do
    merged |> admitted_rows() |> Map.new(&{&1.path, true})
  end

  @count_query """
  PREFIX bpm: <https://ggen.dev/ontology/beam-process-model#>
  SELECT (COUNT(?h) AS ?n) WHERE {
    ?h a bpm:HandAuthoredSource ;
       bpm:authorshipKind ?kind .
    FILTER(?kind = @KIND@)
  }
  """

  defp kind_count(merged, kind_iri) do
    query = String.replace(@count_query, "@KIND@", iri_literal(kind_iri))

    case Oxigraph.run(merged, query) do
      [row | _] -> int_cell(row, "n")
      [] -> 0
    end
  end

  defp gate_queries(pack_dir) do
    gate_dir = Path.join(pack_dir, "gates")

    gate_dir
    |> File.ls!()
    |> Enum.filter(&String.ends_with?(&1, ".rq"))
    |> Enum.sort()
    |> Enum.filter(&(&1 =~ ~r/^0(50|60|70)_/))
    |> Enum.map(&{Path.rootname(&1), Path.join(gate_dir, &1)})
  rescue
    _ -> []
  end

  # ===========================================================================
  # Turtle emission
  # ===========================================================================

  defp subject_for(merged, prefix, path) do
    base = "hand_authored_" <> slug(path)
    existing = existing_subjects(merged)

    Enum.find_value(0..200, fn i ->
      name = if i == 0, do: base, else: "#{base}_#{i}"
      full = "#{prefix}:#{name}"
      if MapSet.member?(existing, full), do: nil, else: full
    end) ||
      raise RuntimeError,
        message:
          "REFUSED_SUBJECT_EXHAUSTED: no free subject under #{prefix}:#{base} after 200 attempts"
  end

  defp existing_subjects(merged) do
    query = """
    PREFIX bpm: <https://ggen.dev/ontology/beam-process-model#>
    SELECT ?h WHERE { ?h a bpm:HandAuthoredSource . }
    """

    Oxigraph.run(merged, query)
    |> MapSet.new(fn row ->
      iri = cell(row, "h")
      iri |> String.split("#") |> List.last() |> String.split("/") |> List.last()
    end)
  end

  defp slug(path) do
    path
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "_")
    |> String.trim("_")
  end

  defp ttl_block(ind) do
    # Property order matches the reference consumer's own individual blocks:
    # sourcePath, authorshipKind, principal, reason, acceptanceCommand,
    # [acceptancePrerequisite], [contentSha256], admittedAtCommit,
    # [admissionExpires], [sunsetPlan]. Debt kinds always carry sha256 +
    # expiry + sunset plan (gate 050); non-debt kinds carry none of the three
    # UNLESS the caller explicitly provided an expiry (the gate allows it, and
    # silently dropping a caller-provided fact would be dishonest).
    prop_lines =
      [
        prop("bpm:sourcePath", ind.path),
        kind_line(ind.kind_iri),
        prop("bpm:authorizingPrincipal", ind.principal),
        prop("bpm:admissionReason", ind.reason),
        prop("bpm:acceptanceCommand", ind.acceptance_command)
      ] ++
        maybe_prop(ind.acceptance_prerequisite, "bpm:acceptancePrerequisite") ++
        if(ind.debt, do: ["    bpm:contentSha256 \"#{ind.sha}\" ;"], else: []) ++
        ["    bpm:admittedAtCommit \"#{ind.admitted_at}\" ;"] ++
        maybe_prop(ind.expires, "bpm:admissionExpires") ++
        if(ind.debt, do: ["    bpm:sunsetPlan \"#{ttl_escape(ind.sunset_plan)}\" ."], else: [])

    lines = ["#{ind.subject} a bpm:HandAuthoredSource ;" | prop_lines]

    fix_terminators(lines)
    |> Enum.join("\n")
  end

  defp prop(name, value), do: "    #{name} \"#{ttl_escape(value)}\" ;"
  defp kind_line(iri), do: "    bpm:authorshipKind #{iri_literal(iri)} ;"

  defp maybe_prop(nil, _name), do: []
  defp maybe_prop("", _name), do: []
  defp maybe_prop(value, name), do: [prop(name, value)]

  # The last emitted property must terminate with " ." and every other line
  # with " ;" -- independent of which optional lines were emitted. Strip any
  # trailing terminator/whitespace first, then append the right one, so a
  # line authored without a terminator can never slip through.
  defp fix_terminators(lines) do
    lines
    |> Enum.with_index()
    |> Enum.map(fn {line, i} ->
      last? = i == length(lines) - 1

      bare =
        line
        |> String.trim_trailing()
        |> String.trim_trailing(";")
        |> String.trim_trailing(".")
        |> String.trim_trailing()

      if last?, do: bare <> " .", else: bare <> " ;"
    end)
  end

  defp insert_individual(content, ind) do
    lines = String.split(content, "\n")
    block = ttl_block(ind)

    last_idx =
      lines
      |> Enum.with_index()
      |> Enum.filter(fn {line, _i} -> String.contains?(line, "a bpm:HandAuthoredSource") end)
      |> Enum.map(fn {_line, i} -> i end)
      |> List.last()

    case last_idx do
      nil ->
        # No existing individual to anchor on: append at end-of-file. Turtle
        # @prefix declarations are positional but apply to the whole rest of
        # the file, so any prefix declared anywhere earlier is in scope here
        # (and prefix_declared?/2 already verified the subject prefix exists).
        new_content = String.trim_trailing(content, "\n") <> "\n\n" <> block <> "\n"
        {new_content, "appended at end-of-file (no existing bpm:HandAuthoredSource individual)"}

      last_idx ->
        # The block ends at the first line whose trimmed form terminates with
        # "." -- either a standalone "." line or (the reference consumer's own
        # style) the final property line ending inline in " .". The opening
        # line ends with " ;", never ".", so it can never match itself.
        dot_idx =
          lines
          |> Enum.slice(last_idx..-1//1)
          |> Enum.with_index()
          |> Enum.find(fn {line, _} ->
            trimmed = String.trim(line)
            trimmed != "" and String.ends_with?(trimmed, ".")
          end)
          |> case do
            nil ->
              refused_and_halt(
                "REFUSED_ONTOLOGY_MALFORMED_SECTION",
                "no terminating '.' after the last bpm:HandAuthoredSource individual"
              )

            {_line, rel} ->
              last_idx + rel
          end

        # head = everything before the dot line; tail = [dot_line | rest]
        # (rest may be [] when the dot line is the file's last line -- no
        # trailing newline -- so split/Enum.at, never a [dot_line | rest]
        # match). head/dot_line/rest partition the lines exactly once.
        {head, tail} = Enum.split(lines, dot_idx)
        dot_line = Enum.at(tail, 0)
        rest = Enum.drop(tail, 1)

        # The join must end with exactly one trailing newline: a consumer
        # file that does NOT end in a newline (the reference consumer's own
        # ontology.ttl is one) would otherwise leave the new block's final
        # "." line as the last element with no newline, and the NEXT admit's
        # terminator scan would then anchor on it with nothing after it.
        new_content =
          [head, [dot_line, ""], [block], rest]
          |> Enum.concat()
          |> Enum.join("\n")
          |> then(&(String.trim_trailing(&1, "\n") <> "\n"))

        anchor_subject = lines |> Enum.at(last_idx) |> String.split(" ") |> List.first()
        {new_content, "inserted after #{anchor_subject}"}
    end
  end

  defp ttl_escape(s) do
    String.replace(s, ~r{["\\\n\t]}, fn
      "\"" -> "\\\""
      "\\" -> "\\\\"
      "\n" -> "\\n"
      "\t" -> "\\t"
      c -> c
    end)
  end

  # ===========================================================================
  # small shared helpers
  # ===========================================================================

  defp default_ontology, do: "ontology.ttl"
  defp default_pack_dir, do: "vendor/ggen-marketplace/packs/beam4pm-process-model-pack"

  defp default_pack_ontology(opts),
    do: Path.join(opts[:pack_dir] || default_pack_dir(), "ontology.ttl")

  defp roots(opts) do
    case opts[:roots] do
      nil ->
        ~w(src lib gleam/src gleam/test test schema docs/reference infra/gcp/cloudrun infra/gcp/packer)

      "" ->
        ~w(src lib gleam/src gleam/test test schema docs/reference infra/gcp/cloudrun infra/gcp/packer)

      str ->
        String.split(str, " ", trim: true)
    end
  end

  defp relative_admitted_path(nil, _root), do: nil

  defp relative_admitted_path(path, root) when is_binary(path) do
    abs = Path.expand(path)

    case Path.relative_to(abs, root) do
      # not under the root: keep the absolute path; the scope check refuses it
      ^abs -> abs
      rel -> rel
    end
  end

  # The gate script's own marker predicate: first 3 lines, case-insensitive.
  defp marked?(path) do
    path
    |> File.read!()
    |> String.split("\n")
    |> Enum.take(3)
    |> Enum.any?(&String.contains?(String.downcase(&1), "generated by ggen"))
  end

  defp in_scope?(path, roots) do
    Enum.any?(roots, fn root -> path == root or String.starts_with?(path, root <> "/") end)
  end

  defp expiry(opts) do
    case opts[:expires] do
      nil -> nil
      "" -> nil
      value -> if Regex.match?(~r/^\d{4}-\d{2}-\d{2}$/, value), do: value, else: {:invalid, value}
    end
  end

  defp sha256_file!(path) do
    path
    |> File.read!()
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  rescue
    e -> refused_and_halt("REFUSED_SHA_UNCOMPUTABLE", "#{path}: #{Exception.message(e)}")
  end

  defp git_head_short(root) do
    case System.cmd("git", ["rev-parse", "--short", "HEAD"], cd: root, stderr_to_stdout: true) do
      {out, 0} -> String.trim(out)
      _ -> nil
    end
  end

  defp prefix_declared?(content, prefix) do
    Regex.match?(~r/@prefix\s+#{Regex.escape(prefix)}\s*:/, content) or
      Regex.match?(~r/^PREFIX\s+#{Regex.escape(prefix)}\s*:/mi, content)
  end

  # GgenIgniter.Query.Oxigraph returns `[map()]` rows with STRING keys and
  # plain lexical values (Literal::value(); IRIs as bare IRI strings) -- the
  # same normalization every pack template reads. Unbound OPTIONALs simply
  # don't appear as keys, so a missing key is an empty string / nil.
  defp cell(row, key), do: Map.get(row, key) || ""

  defp cell_opt(row, key) do
    case Map.get(row, key) do
      nil -> nil
      "" -> nil
      v -> v
    end
  end

  defp int_cell(row, key) do
    case cell(row, key) do
      "" -> 0
      v -> String.to_integer(v)
    end
  rescue
    _ -> 0
  end

  defp iri_literal(iri) do
    iri = String.trim(iri)

    cond do
      String.starts_with?(iri, "<") and String.ends_with?(iri, ">") -> iri
      String.contains?(iri, ":") -> "<" <> iri <> ">"
      true -> "<https://ggen.dev/ontology/beam-process-model##{iri}>"
    end
  end

  defp blank?(v), do: v in [nil, ""]

  defp pad(true), do: "true "
  defp pad(false), do: "false"

  defp indent(text, prefix),
    do: text |> String.split("\n") |> Enum.map_join("\n", &(prefix <> &1))

  defp first_unknown_flag(argv) do
    Enum.find(argv, fn
      "--" <> _ = flag ->
        flag |> String.split("=", parts: 2) |> hd() |> then(&(&1 not in @known_flags))

      "-" <> _ = flag when byte_size(flag) == 2 ->
        flag not in @known_flags

      _ ->
        false
    end)
  end

  defp print_version_and_halt do
    IO.puts("ggen_igniter #{Mix.Project.config()[:version] || "unknown"}")
    System.halt(0)
  end

  defp print_help_and_halt do
    IO.puts("""
    mix ggen_igniter.hand_authored -- the hand-authored-source admission task

    USAGE
        mix ggen_igniter.hand_authored admit --file PATH --kind NAME --reason TEXT
            --principal TEXT --acceptance-command CMD [--sunset-plan TEXT]
            [--expires YYYY-MM-DD] [--admitted-at-commit SHA] [--acceptance-prerequisite P]
            [--subject-prefix bap] [--no-render] [--dry-run]
        mix ggen_igniter.hand_authored list   [--ontology F] [--pack-dir D]
        mix ggen_igniter.hand_authored check  [--gate-script F] [--gate-arg ARG]

    VERBS
        admit   validate every capability-object law (gates 050/060/070) BEFORE
                writing, then append the bpm:HandAuthoredSource individual to the
                consumer's ontology.ttl and re-render the manifest via ggen sync run
        list    print the admitted set per kind (count/ceiling) and run the pack's
                own 050/060/070 gate queries over the merged graph
        check   run the consumer's rendered shell gate (gate_authorship_check.sh)

    EXIT CODES
        0  success (under admit --dry-run: validated, nothing written)
        1  typed REFUSED_* law refusal / gate failure
        2  invalid invocation (unknown verb or flag, missing --file/--kind)
        3  render requested but the ggen binary is absent (two-step printed)
    """)

    System.halt(0)
  end

  defp invalid_invocation_and_halt(reason, _opts) do
    IO.puts("✘ ggen_igniter.hand_authored: invalid invocation -- #{reason}")
    System.halt(2)
  end

  defp refused_and_halt(code, detail) do
    IO.puts("✘ #{code}: #{detail}")
    System.halt(1)
  end

  defp blocked_render_and_halt(message) do
    IO.puts("▲ BLOCKED_RENDER_NO_GGEN: #{message}")
    System.halt(3)
  end
end
