# GENERATED by ggen_igniter from priv/ggen/reactor-scaffold-pack/ontology.ttl.
# Do not edit. Regenerate with:
#   mix ggen_igniter.sync --pack reactor-scaffold-pack \
#     --out lib/ggen_igniter/reactors/examples/expense_approval_reactor.ex
#
# Practice/dogfood example: a full-featured plain `Reactor` (per ADR-0003,
# never Ash.Reactor) manufactured entirely from ontology data, exercising
# every construct in the real Reactor cheatsheet
# (https://reactor.hexdocs.pm/reactor-cheatsheet.html): input, step
# (argument/value/run/compensate/undo/async?/where/guard/max_retries/
# wait_for), debug, group, switch, compose, collect, map, around, template,
# middlewares, return.
defmodule GgenIgniter.Reactors.Examples.ExpenseApprovalReactor do
  @moduledoc """
  Manufactured example Reactor demonstrating the full plain-Reactor DSL
  surface documented at
  https://reactor.hexdocs.pm/reactor-cheatsheet.html — the same primitives
  `GgenIgniter.Reactors.ReconcileReactor` itself uses in production.

  Regenerate via `mix ggen_igniter.sync --pack reactor-scaffold-pack
  --out lib/ggen_igniter/reactors/examples/expense_approval_reactor.ex`.
  Never hand-edit this file — edit `priv/ggen/reactor-scaffold-pack/ontology.ttl`
  instead.
  """
  use Reactor

  middlewares do
    middleware(Reactor.Middleware.Telemetry)
  end

  input(:email)
  input(:amount)
  input(:card_token)

  step :fetch_user do
    argument(:email, input(:email))
    argument(:requested_currency, value("USD"))
    async?(false)

    run(fn %{email: email, requested_currency: _currency}, _context ->
      case GgenIgniter.Reactors.Examples.Support.fetch_user(email) do
        {:ok, user} -> {:ok, user}
        {:error, reason} -> {:error, reason}
      end
    end)
  end

  step :validate_user do
    argument(:user, result(:fetch_user))
    async?(false)
    max_retries(3)

    run(fn %{user: user}, _context ->
      if user.active? do
        {:ok, user}
      else
        {:error, :inactive_user}
      end
    end)

    where(&(&1.user != nil))

    guard(fn %{user: user}, _context ->
      if is_nil(user) do
        {:halt, {:error, :no_user}}
      else
        :cont
      end
    end)
  end

  step :charge_payment do
    argument(:user, result(:validate_user))
    argument(:amount, input(:amount))
    argument(:card_token, input(:card_token))
    async?(true)

    run(fn %{user: user, amount: amount, card_token: card_token}, _context ->
      GgenIgniter.Reactors.Examples.Support.charge(user, amount, card_token)
    end)

    compensate(fn _reason, %{amount: amount, card_token: card_token}, _context ->
      GgenIgniter.Reactors.Examples.Support.refund(card_token, amount)
      :ok
    end)

    undo(fn charge, %{card_token: card_token}, _context ->
      GgenIgniter.Reactors.Examples.Support.refund(card_token, charge.amount)
      :ok
    end)

    wait_for(:fetch_user)
  end

  step :send_receipt do
    argument(:user, result(:validate_user))
    argument(:charge, result(:charge_payment))
    async?(true)

    run(fn %{user: user, charge: charge}, _context ->
      GgenIgniter.Reactors.Examples.Support.send_receipt(user, charge)
    end)
  end

  debug :log_charge do
    argument(:charge, result(:charge_payment))
    argument(:message, value("charge completed"))
  end

  group :audit_group do
    argument(:charge, result(:charge_payment))
    before_all(&GgenIgniter.Reactors.Examples.Support.audit_before/3)
    after_all(&GgenIgniter.Reactors.Examples.Support.audit_after/1)

    step :record_audit do
      argument(:charge, input(:charge))

      run(fn %{charge: charge}, _context ->
        {:ok, "audited #{charge.amount}"}
      end)
    end
  end

  switch :route_by_amount do
    on(input(:amount))

    matches? &(&1 > 1000) do
      return(:flag_large)

      step :flag_large do
        run(fn _args, _context -> {:ok, :large} end)
      end
    end

    default do
      return(:flag_normal)

      step :flag_normal do
        run(fn _args, _context -> {:ok, :normal} end)
      end
    end
  end

  compose :sub_receipt, GgenIgniter.Reactors.Examples.ReceiptSubReactor do
    argument(:charge, result(:charge_payment))
  end

  collect :summary do
    argument(:user, result(:validate_user))
    argument(:charge, result(:charge_payment))
    argument(:notified, result(:notify_admins))

    transform(fn inputs ->
      %{user: inputs.user, charge: inputs.charge, notified: inputs.notified}
    end)
  end

  map :notify_admins do
    source(value(["ops@example.com", "audit@example.com"]))
    batch_size(2)
    allow_async?(true)

    step :notify do
      argument(:email, element(:notify_admins))
      run(fn %{email: email}, _context -> {:ok, "notified #{email}"} end)
    end
  end

  around :with_logging, &GgenIgniter.Reactors.Examples.Support.with_logging/4 do
    step :logged_step do
      run(fn _args, _context -> {:ok, :done} end)
    end
  end

  template :welcome_message do
    argument(:user, result(:validate_user))

    template("""
    Welcome <%= @user.email %>!
    """)
  end

  return(:charge_payment)
end
