defmodule GgenIgniter.DoctorFixes do
  @moduledoc """
  Real, reusable implementations of the four project-hygiene fixes that
  `mix ggen_igniter.doctor --fix` applies to the CURRENT project (the real
  consumer app `doctor` is invoked inside -- not a scaffolded test harness).

  These started life as hand-rolled helpers in
  `test/e2e/support/e2e_case.ex` (`relax_scaffolded_igniter_dep!/1`,
  `relax_scaffolded_sourceror_dep!/1`, `add_dcatr_env_config!/1`,
  `add_ash_domains_config!/3`), written for one specific scaffolded-app
  shape (an `igniter.new --install ash,ash_phoenix --with phx.new`
  fixture with exact, hard-coded version strings). This module extracts the
  same real fix classes into general-purpose, real production code that
  works against ANY real consumer project's `mix.exs`/`config/config.exs`/
  `lib/` tree, not just that one fixture shape -- version requirements and
  `:only` values are detected from the file's real content rather than
  assumed.

  Every public function here takes an explicit `project_dir` (the directory
  to operate on) rather than reading `File.cwd!()` or `Mix.Project.config()`
  internally, so it is trivially testable against a real temp directory
  fixture (Chicago-style: real files on disk, real assertions on the
  resulting file content, no mocks) independent of whatever project is
  actually loaded as the current `Mix.Project`.

  ## Contract shared by every `check_*/fix_*!` pair

    * `check_*` is read-only: it inspects real files and returns
      `{:ok, message}` (nothing wrong), `{:fixable, message}` (a real,
      recognized problem `fix_*!` can safely repair), or
      `{:unrecognized, message}` (a real problem exists, but its exact
      shape isn't one this module can safely rewrite without guessing).
    * `fix_*!` re-runs the same detection, and:
        - no-ops with `{:ok, message}` if there was nothing to fix,
        - applies the fix and returns `{:fixed, message}` if it was
          `:fixable`,
        - `raise`s a `RuntimeError` with the same discipline as the
          original `e2e_case.ex` helpers ("raise a clear error rather than
          guess") if the real shape was `:unrecognized` -- it NEVER
          silently no-ops on a real problem, and never regex-rewrites a
          shape it doesn't precisely recognize.
  """

  @config_relpath "config/config.exs"
  @import_config_marker "import_config \"\#{config_env()}.exs\""

  # ---------------------------------------------------------------------
  # Fix 1 & 2: relax an `:only`-restricted `igniter`/`sourceror` dependency
  # ---------------------------------------------------------------------

  @doc """
  Checks whether `project_dir`'s own `mix.exs` declares `dep` (e.g.
  `:igniter` or `:sourceror`) with an `:only` restriction (any value --
  `only: [:dev, :test]`, `only: :test`, etc.), which is the same real
  conflict class this session hit repeatedly: `ggen_igniter` itself needs
  `:igniter`/`:sourceror` unconditionally (every consuming app, every
  `Mix.env/0`), so a consumer's own `:only`-restricted direct declaration of
  the same dependency causes Mix's resolver to refuse ("Dependencies have
  diverged").

  Only recognizes a single-line dependency tuple of the shape
  `{:dep, "VERSION_REQ", only: ONLY_VALUE}` (the real shape generated by
  `igniter.new`/`phx.new`, and the common hand-written shape). Returns
  `{:unrecognized, message}` rather than guessing if `dep` is declared but
  in some other shape (e.g. `only:` combined with other keys in an order
  this module can't safely strip, or a multi-clause/computed dependency
  spec).
  """
  @spec check_dep_only(Path.t(), atom()) ::
          {:ok, String.t()} | {:fixable, String.t()} | {:unrecognized, String.t()}
  def check_dep_only(project_dir, dep) do
    mix_exs_path = Path.join(project_dir, "mix.exs")
    source = File.read!(mix_exs_path)

    case locate_dep_tuple(source, dep) do
      {:error, :no_deps_fn} ->
        {:unrecognized, "could not locate a deps/0 function body in #{mix_exs_path}"}

      {:ok, :not_declared} ->
        {:ok, "#{dep} is not directly declared in #{mix_exs_path} (nothing to relax)"}

      {:ok, {:tuple, tuple_text}} ->
        if Regex.match?(~r/\bonly:/, tuple_text) do
          case strip_only(tuple_text) do
            nil ->
              {:unrecognized,
               "found a :#{dep} dependency with an `only:` restriction in #{mix_exs_path}, " <>
                 "but its exact shape was not recognized: #{String.trim(tuple_text)}"}

            _fixed ->
              {:fixable,
               "#{dep} dependency in #{mix_exs_path} is restricted (#{String.trim(tuple_text)}) " <>
                 "-- ggen_igniter needs :#{dep} unconditionally, in every Mix.env"}
          end
        else
          {:ok, "#{dep} dependency in #{mix_exs_path} has no :only restriction"}
        end
    end
  end

  @doc """
  Applies the fix `check_dep_only/2` detects: rewrites `project_dir`'s
  `mix.exs`, removing the `:only` restriction from `dep`'s dependency tuple
  (and only that -- any other options on the same tuple, e.g. `runtime:
  false`, are preserved) via a precise single-occurrence text replacement of
  the exact tuple matched, never a full-file regex rewrite.

  Raises a `RuntimeError` instead of guessing if the real shape isn't one
  `check_dep_only/2` recognizes.
  """
  @spec fix_dep_only!(Path.t(), atom()) :: {:ok, String.t()} | {:fixed, String.t()}
  def fix_dep_only!(project_dir, dep) do
    case check_dep_only(project_dir, dep) do
      {:ok, msg} ->
        {:ok, msg}

      {:unrecognized, msg} ->
        raise RuntimeError, msg

      {:fixable, _msg} ->
        mix_exs_path = Path.join(project_dir, "mix.exs")
        source = File.read!(mix_exs_path)
        {:ok, {:tuple, tuple_text}} = locate_dep_tuple(source, dep)
        fixed_tuple_text = strip_only(tuple_text)

        updated = String.replace(source, tuple_text, fixed_tuple_text, global: false)
        File.write!(mix_exs_path, updated)

        {:fixed,
         "relaxed :#{dep} dependency in #{mix_exs_path}: `#{String.trim(tuple_text)}` -> " <>
           "`#{String.trim(fixed_tuple_text)}`"}
    end
  end

  # Locates the `defp deps do ... end` / `def deps do ... end` function body
  # in a real mix.exs source string, then finds `dep`'s own dependency tuple
  # inside it. Returns `{:error, :no_deps_fn}` if no deps/0 function body can
  # be found at all, `{:ok, :not_declared}` if `dep` isn't in the list, or
  # `{:ok, {:tuple, text}}` with the exact matched tuple text (a real
  # substring of `source`, suitable for a precise `String.replace/4`).
  defp locate_dep_tuple(source, dep) do
    case Regex.run(~r/def(?:p)?\s+deps\s+do\s*\n(.*?)\n[ \t]*end/s, source) do
      nil ->
        {:error, :no_deps_fn}

      [_, deps_body] ->
        dep_re = ~r/\{\s*:#{Regex.escape(to_string(dep))}\s*,[^{}]*\}/

        case Regex.run(dep_re, deps_body) do
          nil -> {:ok, :not_declared}
          [tuple_text] -> {:ok, {:tuple, tuple_text}}
        end
    end
  end

  # Strips a recognized `only: ...` keyword pair out of a single dependency
  # tuple's text, preserving every other option on the tuple. Returns `nil`
  # (never a guess) if `only:` is present but not in a recognized position.
  defp strip_only(tuple_text) do
    only_value = ~S/(?:\[[^\]]*\]|:[a-zA-Z_][a-zA-Z0-9_]*)/

    cond do
      Regex.match?(~r/,\s*only:\s*#{only_value}\s*,/, tuple_text) ->
        Regex.replace(~r/,\s*only:\s*#{only_value}\s*,/, tuple_text, ",", global: false)

      Regex.match?(~r/,\s*only:\s*#{only_value}\s*\}\z/, tuple_text) ->
        Regex.replace(~r/,\s*only:\s*#{only_value}\s*\}\z/, tuple_text, "}", global: false)

      true ->
        nil
    end
  end

  # ---------------------------------------------------------------------
  # Fix 3: missing `config :dcatr, env: ...` (needed transitively by :gno)
  # ---------------------------------------------------------------------

  @doc """
  Checks whether `project_dir` needs a `config :dcatr, env: ...` entry.

  `:gno`'s own `Gno.Store.Adapters.Fuseki` calls `DCATR.Manifest.env/1` at
  compile time, which raises unless `config :dcatr, env: ...` (or the
  `DCATR_ENV`/`MIX_ENV` OS environment variable) is set. Only relevant if
  `:gno` or `:dcatr` is actually present in the CURRENT project's own
  dependency tree (checked the same way `ggen_igniter.doctor`'s existing
  `check_deps/1` checks required deps: `Application.ensure_loaded/1` +
  `Application.spec/2`).
  """
  @spec check_dcatr_env_config(Path.t()) :: {:ok, String.t()} | {:fixable, String.t()}
  def check_dcatr_env_config(project_dir) do
    config_path = Path.join(project_dir, @config_relpath)

    cond do
      not (app_loaded?(:gno) or app_loaded?(:dcatr)) ->
        {:ok,
         ":gno/:dcatr not present in the dependency tree -- config :dcatr, env: ... not needed"}

      dcatr_env_configured?(config_path) ->
        {:ok, "config :dcatr, env: ... already present in #{config_path}"}

      true ->
        {:fixable,
         ":gno/:dcatr present in the dependency tree but config :dcatr, env: ... is missing " <>
           "from #{config_path}"}
    end
  end

  @doc """
  Applies the fix `check_dcatr_env_config/1` detects: inserts
  `config :dcatr, env: Mix.env()` into `project_dir`'s `config/config.exs`.

  Insertion strategy (never a full-file rewrite):

    * if the file already ends with the standard `phx.new`-generated
      `import_config "\#{config_env()}.exs"` marker, insert immediately
      before it (so per-env overrides in `dev.exs`/`test.exs`/`prod.exs`
      still take effect after this base value, matching Phoenix's own
      convention);
    * else if the file exists but has no such marker, append at the end;
    * else (no `config/config.exs` at all) create a minimal new one.

  This never raises: every branch is a safe, additive text insertion, not a
  guess about existing content's shape.
  """
  @spec fix_dcatr_env_config!(Path.t()) :: {:ok, String.t()} | {:fixed, String.t()}
  def fix_dcatr_env_config!(project_dir) do
    case check_dcatr_env_config(project_dir) do
      {:ok, msg} ->
        {:ok, msg}

      {:fixable, _msg} ->
        config_path = Path.join(project_dir, @config_relpath)
        dcatr_config = "config :dcatr, env: Mix.env()\n\n"

        write_config_insertion!(config_path, dcatr_config)

        {:fixed, "added `config :dcatr, env: Mix.env()` to #{config_path}"}
    end
  end

  defp dcatr_env_configured?(config_path) do
    case File.read(config_path) do
      {:ok, content} -> Regex.match?(~r/config\s+:dcatr\s*,\s*env:/, content)
      {:error, _} -> false
    end
  end

  # ---------------------------------------------------------------------
  # Fix 4: Ash domain modules missing from `config :OTP_APP, ash_domains:`
  # ---------------------------------------------------------------------

  @doc """
  Checks `project_dir`'s `lib/` tree for modules that `use Ash.Domain`
  (a real textual scan -- these fixture/consumer trees are not necessarily
  compiled, so this deliberately does not require `Code.ensure_loaded?/1`)
  and reports any that are missing from
  `config :OTP_APP, ash_domains: [...]` in `config/config.exs`, where
  `OTP_APP` is `project_dir`'s own `mix.exs` `app:` value.

  Returns `{:unrecognized, message}` (never guesses) if
  `config :OTP_APP, ...ash_domains: ...` is present but its value isn't a
  simple literal list this module can safely merge into.
  """
  @spec check_ash_domains(Path.t()) ::
          {:ok, String.t()} | {:fixable, String.t()} | {:unrecognized, String.t()}
  def check_ash_domains(project_dir) do
    domains = discover_ash_domain_modules(project_dir)

    if domains == [] do
      {:ok, "no `use Ash.Domain` modules found under #{Path.join(project_dir, "lib")}"}
    else
      otp_app = read_otp_app!(project_dir)

      case registered_ash_domains(project_dir, otp_app) do
        {:error, reason} ->
          {:unrecognized, reason}

        {:ok, registered} ->
          missing = domains -- registered

          if missing == [] do
            {:ok,
             "all #{length(domains)} Ash domain module(s) already registered in " <>
               "config :#{otp_app}, ash_domains: [...]"}
          else
            {:fixable,
             "#{length(missing)} Ash domain module(s) not registered in config :#{otp_app}, " <>
               "ash_domains: [...]: #{Enum.join(missing, ", ")}"}
          end
      end
    end
  end

  @doc """
  Applies the fix `check_ash_domains/1` detects: registers every missing
  Ash domain module in `project_dir`'s `config :OTP_APP, ash_domains:
  [...]`.

    * if no `ash_domains:` entry exists yet for this OTP app, inserts a new
      `config :OTP_APP, ash_domains: [...]` block (same insertion strategy
      as `fix_dcatr_env_config!/1`);
    * if one already exists as a simple literal list, merges the missing
      module(s) into it via a precise, minimal in-place text replacement of
      just the bracketed list contents -- every other line of the file is
      untouched.

  Raises a `RuntimeError` (never guesses/overwrites) if an existing
  `ash_domains:` value isn't a simple literal list.
  """
  @spec fix_ash_domains!(Path.t()) :: {:ok, String.t()} | {:fixed, String.t()}
  def fix_ash_domains!(project_dir) do
    case check_ash_domains(project_dir) do
      {:ok, msg} ->
        {:ok, msg}

      {:unrecognized, msg} ->
        raise RuntimeError, msg

      {:fixable, _msg} ->
        otp_app = read_otp_app!(project_dir)
        domains = discover_ash_domain_modules(project_dir)
        {:ok, registered} = registered_ash_domains(project_dir, otp_app)
        missing = domains -- registered

        config_path = Path.join(project_dir, @config_relpath)
        apply_ash_domains_fix!(config_path, otp_app, registered, missing)

        {:fixed,
         "registered #{length(missing)} Ash domain module(s) in #{config_path}: " <>
           "#{Enum.join(missing, ", ")}"}
    end
  end

  defp discover_ash_domain_modules(project_dir) do
    project_dir
    |> Path.join("lib/**/*.ex")
    |> Path.wildcard()
    |> Enum.flat_map(&extract_ash_domain_modules/1)
    |> Enum.uniq()
  end

  defp extract_ash_domain_modules(file_path) do
    content = File.read!(file_path)

    if String.contains?(content, "use Ash.Domain") do
      content
      |> String.split("\n")
      |> Enum.reduce({[], nil}, fn line, {found, current_module} ->
        cond do
          match = Regex.run(~r/^\s*defmodule\s+([A-Z][A-Za-z0-9_.]*)\s+do/, line) ->
            [_, mod] = match
            {found, mod}

          Regex.match?(~r/^\s*use\s+Ash\.Domain\b/, line) and current_module != nil ->
            {[current_module | found], current_module}

          true ->
            {found, current_module}
        end
      end)
      |> elem(0)
    else
      []
    end
  end

  defp read_otp_app!(project_dir) do
    mix_exs_path = Path.join(project_dir, "mix.exs")
    source = File.read!(mix_exs_path)

    case Regex.run(~r/app:\s*:([a-zA-Z_][a-zA-Z0-9_]*)/, source) do
      [_, app] ->
        app

      nil ->
        raise RuntimeError,
              "could not find `app: :your_app` in #{mix_exs_path} -- refusing to guess the OTP app name"
    end
  end

  defp ash_domains_key_regex(otp_app) do
    ~r/config\s+:#{otp_app}\b(?:(?!\nconfig\s).)*?ash_domains:/s
  end

  defp ash_domains_block_regex(otp_app) do
    ~r/config\s+:#{otp_app}\b(?:(?!\nconfig\s).)*?ash_domains:\s*\[[^\]]*\]/s
  end

  defp registered_ash_domains(project_dir, otp_app) do
    config_path = Path.join(project_dir, @config_relpath)

    case File.read(config_path) do
      {:error, _} ->
        {:ok, []}

      {:ok, content} ->
        cond do
          not Regex.match?(ash_domains_key_regex(otp_app), content) ->
            {:ok, []}

          match = Regex.run(ash_domains_block_regex(otp_app), content) ->
            [block] = match
            {:ok, extract_domain_names(block)}

          true ->
            {:error,
             "found `config :#{otp_app}, ...ash_domains: ...` in #{config_path} but its " <>
               "value isn't a simple literal list -- refusing to guess how to merge into it"}
        end
    end
  end

  defp extract_domain_names(ash_domains_block) do
    [_, inner] = Regex.run(~r/\[([^\]]*)\]\z/, ash_domains_block)

    inner
    |> String.split(",")
    |> Enum.map(&String.trim/1)
    |> Enum.reject(&(&1 == ""))
  end

  defp apply_ash_domains_fix!(config_path, otp_app, registered, missing) do
    case File.read(config_path) do
      {:ok, content} ->
        case Regex.run(ash_domains_block_regex(otp_app), content) do
          [existing_block] ->
            new_inner = Enum.join(registered ++ missing, ", ")
            new_block = Regex.replace(~r/\[[^\]]*\]\z/, existing_block, "[#{new_inner}]")

            updated = String.replace(content, existing_block, new_block, global: false)
            File.write!(config_path, updated)

          nil ->
            domains_config = "config :#{otp_app}, ash_domains: [#{Enum.join(missing, ", ")}]\n\n"
            write_config_insertion!(config_path, domains_config, content)
        end

      {:error, _} ->
        domains_config = "config :#{otp_app}, ash_domains: [#{Enum.join(missing, ", ")}]\n\n"
        write_config_insertion!(config_path, domains_config)
    end
  end

  # ---------------------------------------------------------------------
  # Shared config/config.exs insertion helper (fixes 3 and 4)
  # ---------------------------------------------------------------------

  # Inserts `config_block` into the config file at `config_path`: before the
  # standard phx.new `import_config` marker if present, else appended at the
  # end of the (already-read, if given) `content`, else a fresh minimal file
  # is created. Never touches any content other than adding this block.
  defp write_config_insertion!(config_path, config_block, content \\ nil) do
    content = content || (File.exists?(config_path) && File.read!(config_path))

    updated =
      cond do
        content && String.contains?(content, @import_config_marker) ->
          String.replace(content, @import_config_marker, config_block <> @import_config_marker,
            global: false
          )

        content ->
          String.trim_trailing(content) <> "\n\n" <> config_block

        true ->
          "import Config\n\n" <> config_block
      end

    File.mkdir_p!(Path.dirname(config_path))
    File.write!(config_path, updated)
  end

  defp app_loaded?(app) do
    Application.ensure_loaded(app)
    Application.spec(app, :vsn) != nil
  end
end
